### ISSUE TITLE
I can't join an existing game?

### ISSUE THREAD

**Issue by nevans224** [thyer/CS340winter2016#109]
Guys this is weird... I know we've been able to join a game before but now it won't let me join an existing game. (I may have tried to join the game before the creator joined it?)

I took pictures of what was going on
Picture 1 - my username and password
Picture 2 - Game I want to join
Picture 3 - I choose a color (green)
Picture 4 - Player waiting screen but I'm not on it

The command line spits out this over and over again:

Caused by: server.ServerException: doGet failed: /game/model?version=-1 (http code 400)
        at server.ServerProxy.get(ServerProxy.java:146)
        ... 4 more
server.ServerException: doGet failed: doGet failed: /game/model?version=-1 (http code 400)
        at server.ServerProxy.get(ServerProxy.java:150)
        at server.ServerProxy.getModel(ServerProxy.java:214)
        at server.ServerPoller$Poll.run(ServerPoller.java:51)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)

**Comment by nevans224** [comment]
<img width="525" alt="game i m trying to join" src="https://cloud.githubusercontent.com/assets/11450031/13472199/04c85a40-e071-11e5-98fc-e92018d830ef.PNG">
<img width="238" alt="i_choose_green" src="https://cloud.githubusercontent.com/assets/11450031/13472201/04cc13ba-e071-11e5-8aea-2c7071bf8754.PNG">
<img width="331" alt="i_guess_i m_not_in" src="https://cloud.githubusercontent.com/assets/11450031/13472200/04cb79f0-e071-11e5-84ab-353103a5a150.PNG">
<img width="502" alt="login" src="https://cloud.githubusercontent.com/assets/11450031/13472198/04c81b16-e071-11e5-84bc-0dced943aa32.PNG">

**Comment by hunterrees** [comment]
@nevans224 were there any errors on the terminal before the doGet one that kept printing over and over again

**Comment by nevans224** [comment]
@hunterrees There was a arrayindexoutofbounds error but We get that somewhat frequently and doesn't usually affect anything. This one is weird. My advice is to create a game and let someone join before the creator and see what happens. Hopefully that reproduces the error.

**Comment by hunterrees** [comment]
@nevans224 Had other people joined that game besides Tclawson before you tried to join?
