### ISSUE TITLE
Place a Settlement Modal can be opened when it isn't your turn

### ISSUE THREAD

**Issue by benya16** [thyer/CS340winter2016#11]
**Description**
If you have the correct amount of resources to build a settlement, the button is enabled to open the Build a Settlement modal even when it isn't your turn. You can't actually place a settlement at least, so it isn't technically affecting gameplay.

**Reproduce**
1. Play the game until you have enough resources to build a settlement (but don't build one)
2. Wait until it isn't your turn and you can still open the modal

**Comment by thyer** [comment]
@benya16 does the button do anything when clicked? Any errors thrown or behaviors evident?
