### ISSUE TITLE
Places robber twice when rolling a seven

### ISSUE THREAD

**Issue by hunterrees** [thyer/CS340winter2016#111]
I roll a seven and then place the robber, and steal, but then the place robber modal appears again but I can't place the robber again. I can then cancel this second robber action (the roll modal is still present when the second robber is canceled). There was one time this error didn't occur when I had to discard

**Comment by panzertime** [comment]
When this happens, the second robber modal doesn't actually affect the game; only the first one does.  Maybe we can move this to a P4?
