### ISSUE TITLE
Trade Ports

### ISSUE THREAD

**Issue by ztnelson01** [thyer/CS340winter2016#119]
For Maritime trade it looks like some of the 2:1 ports are working (brick port worked but wood port didn't). 3:1 ports aren't working. I can't trade when I should be able to because of this problem.

**Comment by hunterrees** [comment]
![thumb_img_0540_1024](https://cloud.githubusercontent.com/assets/16613772/13472895/2102dda4-e074-11e5-87df-01ecf002243d.jpg)
We are red in this case

**Comment by panzertime** [comment]
Seems like ore works fine.  Could take a while to check all of these.

**Comment by ztnelson01** [comment]
Yeah, sorry I wasn't more thorough in testing all of the maritime trade
resources. It could have something to do with another factor at play, but
sometimes maritime trade wasn't being allowed even though I was on a port.
I'm not sure why some ports would work while others don't. Sorry >_<

**Comment by panzertime** [comment]
Sheep's fine too.

(I'm making these comments as notes to myself, you don't need to worry about them)

**Comment by panzertime** [comment]
So I managed to get a 3:1 to work with bricks

**Comment by panzertime** [comment]
This appears to be fixed

**Comment by thyer** [comment]
@panzertime was this bug ever reproducible? Also, if you can figure out that it was related to another issue, if you would mark that here? That allows for a bit more mercy since this is marked as a P3 and we'd hate to take off more points than we need to.

**Comment by panzertime** [comment]
It was reproduced, I was using the wrong client.

**Comment by panzertime** [comment]
This is fixed now
