### ISSUE TITLE
Null Pointer Exception in the Poller

### ISSUE THREAD

**Issue by benya16** [thyer/CS340winter2016#124]
**Description**
Occasionally there is a null pointer exception when finishing a turn. In one client it will show that it is one person's turn, but in another client it will show that it is a different person's turn. The null pointer is in the Poller. 

![image](https://cloud.githubusercontent.com/assets/13576467/13472670/32111b52-e073-11e5-8104-544f1da48f44.png)

![image](https://cloud.githubusercontent.com/assets/13576467/13472721/5dfe04e6-e073-11e5-9e64-526745f4e6e8.png)

It looks like after I tried buying a development card there was a null pointer exception thrown.

**Reproduce**
Create a game with at least a couple players (I had two players and two AI). Try buying some development cards and seeing if it throws a null pointer exception in the poller.

**Comment by thelaurence** [comment]
I made a half dozen attempts at the reproduction procedure described above and was unable to get it to throw a NullPointerException.
