### ISSUE TITLE
Team 13 Stress Test fail - unlimited Domestic Trade resources

### ISSUE THREAD

**Issue by jrwalther** [thyer/CS340winter2016#126]
Even though there are only 19 cards of each resource, I can ask for at least 1000 resources from any one player. Theoretically I could keep adding the number until it overloads but I really didn't have the time for that.

**Comment by bbarney7** [comment]
their demo allows this

**Comment by bbarney7** [comment]
plus its not a stress test unless you actually get it to crash

**Comment by mcrowder65** [comment]
marked invalid because this is allowed on demo client.

**Comment by panzertime** [comment]
Just because the demo client does it doesn't mean yours should.

**Comment by mcrowder65** [comment]
Marked invalid because this behavior doesn't matter - you can ask to trade as many resources as you want, the other player will never be able to accept it though.

**Comment by panzertime** [comment]
Marked P4 for that reason.

**Comment by mcrowder65** [comment]
That's fair. Btw I'm marking fixed on other bugs just so my teammates know that I've fixed them.

**Comment by thyer** [comment]
Marking as invalid - nothing prevents you in the real game from turning to your buddy and telling him, "I'll give you a sheep if you give me 1,000 brick."
