### ISSUE TITLE
Team 13 Robber does not appear when game is started

### ISSUE THREAD

**Issue by jrwalther** [thyer/CS340winter2016#128]
When the first screen comes up, the map is displayed except for the robber. The robber only appears after I place the robber.

**Comment by jrwalther** [comment]
This problem is also there with 2 clients. As I play as the same player on two clients - the client that hasnt made any actions won't see the robber although the rest of the game updates.

**Comment by thyer** [comment]
Knocking this down a priority level - I think it's more a stylistic thing than incorrect behavior.

**Comment by mcrowder65** [comment]
marked invalid after talking to Bentz
