### ISSUE TITLE
TradeWithMyself

### ISSUE THREAD

**Issue by ztnelson01** [thyer/CS340winter2016#129]
I can offer a domestic trade without any players selected.
![image](https://cloud.githubusercontent.com/assets/16672513/13472882/0d86f666-e074-11e5-9188-0cca0b3a2293.png)
This causes me to trade with myself. It brings up the waiting modal, then closes it, and then opens up the trade offer overlay, allowing me to choose to accept or decline the request I sent to myself.

**Comment by panzertime** [comment]
I think this is an easy fix
