### ISSUE TITLE
Cannot build road where I should.

### ISSUE THREAD

**Issue by ZackMagleby** [thyer/CS340winter2016#130]
![bug1](https://cloud.githubusercontent.com/assets/16657196/13472791/a1ca05b2-e073-11e5-8136-069c0d3da03d.png)

**Comment by hunterrees** [comment]
@ZackMagleby  Were there any errors previous to this in the same instance of the client?

**Comment by ZackMagleby** [comment]
Yes, Todd's bug here: https://github.com/thyer/CS340winter2016/issues/131 was in the same game, and most likely related.

**Comment by thyer** [comment]
I agree with the invalid label - unless @ZackMagleby can show that the same behavior occurs without the implications of issue #131, we can't double count issues. Kudos to you, though on documenting both the issue and its implications.
