### ISSUE TITLE
Maps not properly synced

### ISSUE THREAD

**Issue by tclaw46** [thyer/CS340winter2016#131]
Red Player(Zack) has roads build that do not show up on Orange player's(Todd) screen.
Finished Zack's turn and roads have still not appeared. Both pictures were taken on the same turn.
![capture](https://cloud.githubusercontent.com/assets/9815905/13472945/66b8de02-e074-11e5-9582-cd8f6e32c5de.PNG)
This is Todd's screen after Zack has finished turn. 
![bug2](https://cloud.githubusercontent.com/assets/9815905/13472979/7ea292ba-e074-11e5-97e4-89dfef52b2da.png)
This is Zack's screen after Zack has finished turn.

**Comment by hunterrees** [comment]
@ZackMagleby did the console throw any exceptions when you built that last road?
