### ISSUE TITLE
Team 19 - Can't end turn

### ISSUE THREAD

**Issue by tiubrian** [thyer/CS340winter2016#132]
register a new player
create a new game with 3 ai's
run through set up phase
can't end your first turn

sometimes it works, sometimes it doesn't

**Comment by panzertime** [comment]
Have you got any more information about how to reproduce this?  Is it truly intermittent?

**Comment by tiubrian** [comment]
Yeah if you register with a new account, it happens every time. If you use
a default one like sam or brooke, it doesn't happen

2016-03-03 8:52 GMT-07:00 panzertime <notifications@github.com>:

> Have you got any more information about how to reproduce this? Is it truly
> intermittent?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thyer/CS340winter2016/issues/132#issuecomment-191823396>
> .
>



-- 
Brian Tiu

**Comment by joshuahaertel** [comment]
Great, thank you for the detailed feedback. Unless there is a difference between this and bug #113 I am going to mark the other as a duplicate.

**Comment by tiubrian** [comment]
oops i didn't realize that already put that down. i think it's the same
bug. thanks for letting me know

2016-03-03 11:35 GMT-07:00 joshuahaertel <notifications@github.com>:

> Great, thank you for the detailed feedback. Unless there is a difference
> between this and bug #113
> <https://github.com/thyer/CS340winter2016/issues/113> I am going to mark
> the other as a duplicate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thyer/CS340winter2016/issues/132#issuecomment-191903341>
> .
>



-- 
Brian Tiu

**Comment by joshuahaertel** [comment]
It got closed though, so I think we're fine.
