### ISSUE TITLE
Unable to rejoin ongoing game

### ISSUE THREAD

**Issue by tclaw46** [thyer/CS340winter2016#138]
Tclaw46 left game to select different color. tclaw46 was unable to rejoin game. Zack is still a part of the game. Game has two humans and two AI.
![bug1-a](https://cloud.githubusercontent.com/assets/9815905/13473297/f9f39ecc-e075-11e5-9936-ff772f94dbef.PNG)

Selected color and clicked join game.

![bug1-b](https://cloud.githubusercontent.com/assets/9815905/13473298/f9f5b75c-e075-11e5-80ce-fa6f8e84fad2.PNG)

Game got stuck at ready to join game. Would not continue.

![capture1](https://cloud.githubusercontent.com/assets/9815905/13473426/8ee598b4-e076-11e5-95c2-ef3a559eb92c.PNG)

This error kept appearing

**Comment by hunterrees** [comment]
Was there an error that appeared before the Server Exception error?

**Comment by tclaw46** [comment]
Sorry the error kept repeating itself so if there was an original error I couldn't find it.
