### ISSUE TITLE
Team 19 - rejoining a game after winning

### ISSUE THREAD

**Issue by rysav** [thyer/CS340winter2016#144]
After you win a game it properly allows me to join/create a new game, but when I join all the settlements/roads/ports are drawn on the map still. I can build stuff on top of them so they arent in the model, but they are on the view.

**Comment by jmbarzee** [comment]
It looks like a lot of teams solved this by just closing the client. I vote we do the same

**Comment by joshuahaertel** [comment]
The problem is that that is not what the spec says to do, furthermore, they can still re-join the game.
