### ISSUE TITLE
Team 19: Clear Trade Overlay

### ISSUE THREAD

**Issue by ztnelson01** [thyer/CS340winter2016#146]
After sending a domestic trade offer the overlay is not cleared completely. So I send a trade to Quin
![domestictradenoclear](https://cloud.githubusercontent.com/assets/16672513/13473910/c7408a32-e078-11e5-9747-3d4f994290dd.png)

then I open domestic trade again. It shows I have quin selected, but if I send another trade without changing who's selected it will attempt to trade with myself.
![tradewithmyself](https://cloud.githubusercontent.com/assets/16672513/13473903/bfbe2198-e078-11e5-9a39-42895f37aa2d.png)

**Comment by jrwalther** [comment]
This is not a different bug than the combination of 116 and 129
