### ISSUE TITLE
Game history not updating correctly

### ISSUE THREAD

**Issue by ZackMagleby** [thyer/CS340winter2016#150]
Finsihed game. tclaw46's last move was building a settlement. Not updated in history.

![bug3](https://cloud.githubusercontent.com/assets/16657196/13474234/481eb2c2-e07a-11e5-9bfb-59d06881be52.png)

**Comment by hunterrees** [comment]
Did building the settlement make tclaw46 win the game?

**Comment by ZackMagleby** [comment]
Yes, on Todd's screen, the final entry was that he build a settlement.
