### ISSUE TITLE
Team 19: Map in Chat?

### ISSUE THREAD

**Issue by ztnelson01** [thyer/CS340winter2016#154]
There's a copy of the image of the map showing up behind the chat. I'm not 100% sure, but I don't think that's supposed to be there.
![mapinchat](https://cloud.githubusercontent.com/assets/16672513/13474438/40050770-e07b-11e5-8999-c98f68911475.png)

**Comment by jrwalther** [comment]
Hey I'm pretty sure this is a problem with Windows and the Chat view itself.

**Comment by jrwalther** [comment]
It appears this way whenever I use Windows to test - whether it is on my client or somebody else's.

**Comment by panzertime** [comment]
I use a Mac and don't have this problem.  I'm leaning towards this being Java's or Windows' problem.
