### ISSUE TITLE
Can build roads and settlements with different colors

### ISSUE THREAD

**Issue by yeyyosing** [thyer/CS340winter2016#170]
Every time I build a settlement or road, it doesn't matter what my color is, it is always orange.

**Comment by emeraldarcher** [comment]
Same thing happens with cities

**Comment by thyer** [comment]
Does this reflect in the server as well? If so, elevating to a P2

**Comment by emeraldarcher** [comment]
I'm not sure how we would determine whether or not it's a bug in the server as well.

**Comment by thyer** [comment]
If you look in the model returned by the server and it reflects the same colors, that suggests that the problem is the client sending the wrong thing, not just displaying the wrong thing.
