### ISSUE TITLE
Problems after rolling a 7 and moving robber

### ISSUE THREAD

**Issue by eaglewyng** [thyer/CS340winter2016#176]
The UI says that I couldn't rob anyone when I should have been able to, and the UI completely freezes up.

![robbing](https://cloud.githubusercontent.com/assets/7014998/13478935/d629ae08-e090-11e5-87a6-f459e8012fb1.PNG)

**Comment by misterpink14** [comment]
I'm having a difficult time reproducing this. Did test1 have wood then? Do you remember the steps you took before this? Just trying to find the bug so I can fix it, thanks!
