### ISSUE TITLE
Lets you place a road that isn't yours

### ISSUE THREAD

**Issue by cbhomestar** [thyer/CS340winter2016#181]
I signed in as the fourth player of a game. It let me place a road for the first player then a settlement for a second player.

<img width="1440" alt="screen shot 2016-03-02 at 4 10 34 pm" src="https://cloud.githubusercontent.com/assets/9063768/13479039/88252af6-e091-11e5-8b53-72fe5a63780f.png">

**Comment by thyer** [comment]
Closing as related to game index issue
