### ISSUE TITLE
Log stops working

### ISSUE THREAD

**Issue by eaglewyng** [thyer/CS340winter2016#186]
The log stopped working at a certain point, and I'm not quite sure how to reproduce it. I will update this issue when I figure it out.
![log](https://cloud.githubusercontent.com/assets/7014998/13479226/b06720c2-e092-11e5-999d-e1484ed41a03.PNG)

Notice how a whole round has gone by, and purple and pink's actions were not recorded (and apparently brown rolled twice in a row).

**Comment by thyer** [comment]
@eaglewyng Parker did you ever manage to dupe this?

**Comment by eaglewyng** [comment]
We were able to do it on two separate computers,  yes. We weren't able to
tell find a pattern between the point where the log stopped working, but in
both cases it did.

**Comment by thyer** [comment]
Team 5 claims it may be a server issue -- I'll validate during TA testing

**Comment by thyer** [comment]
I also managed to duplicate. Removing invalid label.
