### ISSUE TITLE
Roll 2, did not award resource

### ISSUE THREAD

**Issue by farns24** [thyer/CS340winter2016#187]
Brooke Rolled a 2. Brooke had a settlement on the hex for number 2. The resource of space 2, wood, was not given to Brooke. Team4

**Comment by eaglewyng** [comment]
Thank you for submitting that. In the future, it would be very helpful if you could label the reports you submit.

**Comment by matthewfcarlson** [comment]
I suspect this a refresh error on the resource bar, which has since been overhauled.

**Comment by matthewfcarlson** [comment]
I haven't been able to reproduce this as it looks like resources are being awarded correctly. I will keep looking to see if we can reproduce thus

**Comment by eaglewyng** [comment]
Me either. Perhaps the robber was on that tile?

**Comment by thyer** [comment]
I will attempt to reproduce this during TA testing, but sounds like it may have been a fluke.
