### ISSUE TITLE
Dev Card Model not disabling cards when trying to use a card

### ISSUE THREAD

**Issue by mountain01** [thyer/CS340winter2016#188]
Expected:
When a card is selected, all other cards should be disabled.

Actual:
When trying to play dev cards after selecting a card to play I'm still allowed to select a different dev card.

**Comment by sadler-j** [comment]
Based on our understanding of the above expectation, the expected behavior is not discussed in the spec nor in the demo. Therefore, we are considering this invalid. If you feel our understanding is wrong, please clarify the expectation.

**Comment by mountain01** [comment]
Good catch. I had misread the section about disabling the cards on page 18
of the functional spec pdf about playing only one dev card per round.
