### ISSUE TITLE
Domestic Trade controller Trade button never enabled on Valid Trade

### ISSUE THREAD

**Issue by tunadude09** [thyer/CS340winter2016#195]
I've never figured out how to make a trade that will enable the Trade button.... So I can't test any domestic trade functionality.... haha. Domestic Trade messages never update ever either but I'll leave that as a note in this bug instead of making a new one as I'm not sure how important it is.

![image](https://cloud.githubusercontent.com/assets/6475025/13479467/4bf3f74e-e094-11e5-99f9-5a15076f0555.png)

Another example:
![image](https://cloud.githubusercontent.com/assets/6475025/13479478/66064b6e-e094-11e5-8965-ee7bff4f15fe.png)

**Comment by thyer** [comment]
The button works now, but freezes the game. I should elevate to a P2 since additional breakage occurred, but I won't.
