### ISSUE TITLE
Team 4: Domestic Trade Dialog Doesn't Close

### ISSUE THREAD

**Issue by wesleyackerman** [thyer/CS340winter2016#196]
I initiated a trade with one player, trading a single item for another. The other player accepted the trade, but the trade offerer's "un moment" waiting dialog hasn't disappeared.

**Comment by eaglewyng** [comment]
Thanks for reporting this, but we actually hadn't marked this as implemented on the rubric. We WILL fix this, but I'm going to mark this as invalid so we don't get points taken off for it.

**Comment by tunadude09** [comment]
this is fixed, I can't change the labels though

**Comment by thyer** [comment]
I'm going to close this issue as invalid. @eaglewyng @tunadude09 We'll discuss how to hash out points for late implementation during our appointment today.
