### ISSUE TITLE
Trading resources not had

### ISSUE THREAD

**Issue by farns24** [thyer/CS340winter2016#198]
Pete initiated a trade with Brooke.
Pete asked to recieve 2 Wheat and a stone from brooke in exchange for giving 2 sheep.
Brooke did not have 2 wheat and a stone. 
Brooke accepted the trade anyways.
Brooke's trade Modal dismissed.
Mark's screen is frozen.

**Comment by eaglewyng** [comment]
I'm assuming this is for team 4, and I'll label it as such. Let me know if I'm wrong!

**Comment by eaglewyng** [comment]
Marking this as invalid for points because our rubric said that we didn't have this implemented, but we WILL fix this. Thanks for the heads up!

**Comment by tunadude09** [comment]
This is fixed for the record, trade finishes successfully and resources are update right away. Thanks
