### ISSUE TITLE
Maritime traiding for the same resources as that given up.

### ISSUE THREAD

**Issue by farns24** [thyer/CS340winter2016#201]
This might be a bit of a stretch, but in a maritime trade, should a player (In this case, a player that has very poor judgement) be able to trade 4 ore for 1 ore?

**Comment by eaglewyng** [comment]
Since you've submitted a team four issue before, I'm going to assume this is for team 4. Let me know if I'm wrong!

**Comment by eaglewyng** [comment]
This doesn't seem to be a bug. On the spec it has a screenshot of someone trading sheep for sheep (shown below). This might be useful to avoid discarding cards if you think someone will roll a seven in the near future.

![catanmaritime](https://cloud.githubusercontent.com/assets/7014998/13485177/32fb2a54-e0c2-11e5-9fed-a2ae2974225c.PNG)

**Comment by thyer** [comment]
I agree, this bug is invalid. Closing issue.
