### ISSUE TITLE
Game freezes when placing a road

### ISSUE THREAD

**Issue by tunadude09** [thyer/CS340winter2016#205]
The game freezes when trying to place a road.... sorry I'm having trouble reproducing it right now. It's the 4th round of place, I'm the first player to try to build anything. No errors throw, the game just freezes. This might be the same as other logged bugs but I'm just submitted it in case it helps you solve the other ones. The window won't close when I try to close the window. Had to close from terminal

![image](https://cloud.githubusercontent.com/assets/6475025/13479664/cfe50042-e095-11e5-93df-2abf172cf647.png)

**Comment by thyer** [comment]
Claimed to be invalid -- will validate during TA testing

**Comment by thyer** [comment]
I managed to duplicate this, but only as it related to #85 -- same exception got thrown. Marking as duplicate and closing.
