### ISSUE TITLE
Delayed win when building

### ISSUE THREAD

**Issue by mountain01** [thyer/CS340winter2016#207]
I have 9 points and can build a settlement.

Expected:
Build City and have win modal display.

Actual:
Modal does not go away. Hitting cancel makes it go away but the winning modal still is displayed and settlement count has not decremented. I can still build another settlement. Upon doing this the modal still does not disappear until hitting cancel. However this time the winner modal has appeared.

**Comment by eaglewyng** [comment]
Which modal doesn't go away? Sorry, just trying to get a feel for this. Is it the build modal that's not disappearing? Or is it the city placement modal?

**Comment by mountain01** [comment]
The city/settlement placement modal that displays the map. 

Get Outlook




On Wed, Mar 2, 2016 at 9:05 PM -0800, "Parker Ridd" <notifications@github.com> wrote:












Which modal doesn't go away? Sorry, just trying to get a feel for this. Is it the build modal that's not disappearing? Or is it the city placement modal?

**Comment by tunadude09** [comment]
I think you meant 

Expected:
Build Settlement

right? Every time I've tried building a city to win the game has ended correctly. I'll test building a settlement to win.

Before, here I can build either a city or a settlement to win:
![image](https://cloud.githubusercontent.com/assets/6475025/13584394/a9545946-e473-11e5-890c-7a4a22aceaa7.png)

(sorry forgot to take a picture of the place settlement modal, it worked correctly though)

Building a settlement the modal closes but no winning modal is display:
![image](https://cloud.githubusercontent.com/assets/6475025/13584493/1c498430-e474-11e5-82df-56f91c1bbdb9.png)

I couldn't fully recreate the bug but the winning modal should definetely display here

**Comment by mountain01** [comment]
Yes, you're correct. Sorry about that. I keep switching up the two :p

**Comment by tunadude09** [comment]
You're fine :) I confirmed the bug more of less. Update: I ended the game by placing a settlement for point #10 but the winning modal didn't display. After placing one more road the winning dialog finally appeared
