### ISSUE TITLE
Maritime Trade

### ISSUE THREAD

**Issue by misterpink14** [thyer/CS340winter2016#211]
The Maritime Trade button is enabled in Setup phase. It should be disabled.

<img width="542" alt="screen shot 2016-03-02 at 5 27 20 pm" src="https://cloud.githubusercontent.com/assets/9299960/13480665/a1c0c2da-e09c-11e5-9126-7cc96b29afe9.png">

**Comment by thyer** [comment]
Marking as dupe of button activation
