### ISSUE TITLE
Host/Port params not working (JoshP)

### ISSUE THREAD

**Issue by jtmingus** [thyer/CS340winter2016#212]

**Comment by jpp46** [comment]
@jtmingus @thyer 
What do you mean it's not working, when I type "java -jar catan-client.jar" it runs and when I type "java -jar catan-client.jar localhost 8081" it works just fine. I am not sure what isn't working could you explain better, am I misunderstanding the requirement?

**Comment by jtmingus** [comment]
@jpp46 We ran the server on port 8083 and then tried localhost 8083 on your client and it couldn't get a connection. Our guess was that you had it hard coded to be 8081, which is why it worked when you used 8081 as the parameter.

**Comment by jtmingus** [comment]
@jpp46 does that make sense?

**Comment by kking937** [comment]
I guess the demo server doesn't take parameters to assign the host and port.  It is always assigned to localhost and to port 8081 (issue with the given server demo).  So I guess this isn't an issue as long as the server will never be placed on any other host or ports.  @thyer

**Comment by jpp46** [comment]
@jtmingus If it was hard coded to be 8081 then it would always work no matter which port number you put in the reason it doesn't work when you put it 8083 is because the server only runs on 8081, so what your are telling me is that putting in host and port really does work since if you don't use 8081 the expected result is no connection

**Comment by jtmingus** [comment]
@jpp46 Yeah, we realized that. Kevin messaged above letting you know that it's not an issue. Sorry for the confusion

**Comment by thyer** [comment]
@kking937 If you can figure out a way to pass in a host to a server and get it to run on that host, I'll pay you lots of money.
