### ISSUE TITLE
Stealing Cards from someone with no cards (JoshP)

### ISSUE THREAD

**Issue by jtmingus** [thyer/CS340winter2016#216]
If you play the robber on someone that has no cards, it lets you try and steal a card. If you do, it says waiting for other players and the game freezes. You have to exit out to be able to continue the game.

**Comment by jakebrucebrewer** [comment]
@jtmingus Does this happen repeatedly?

**Comment by jtmingus** [comment]
@jakebrucebrewer It happened every single time I tried to steal from someone with no cards. Like 3 different times
