### ISSUE TITLE
Discarding controller appears after discard

### ISSUE THREAD

**Issue by hydn** [thyer/CS340winter2016#22]
**Description**
If I have more than 7 cards after discarding, I am asked to continuously discard until I have less than 7 cards.

**Steps to Reproduce**
1. Start a multiplayer game
2. Acquire 16 or more resources
3. Roll a 7
4. Discard half of your resources before any other player does
5. The discard modal will reappear

**Comment by tclaw46** [comment]
Add a boolean alreadyDiscarded that will check if the player has discarded. If he has then the modal will not appear.
