### ISSUE TITLE
Can't build settlements on first turn after setup

### ISSUE THREAD

**Issue by samuelgc** [thyer/CS340winter2016#220]
Even if the player has the necessary resources, he can not place a settlement in a valid location. 
The place Settlement modal will pop up but all locations are marked invalid and the only option is to cancel the placement.

**Comment by calebtonkinson** [comment]
Question: Did you set up another road? Settlements cannot be on adjacent corners. So if you don't build an additional road there are no valid locations to build a settlement in the first round after setup.
