### ISSUE TITLE
AI can't get longest road

### ISSUE THREAD

**Issue by samuelgc** [thyer/CS340winter2016#221]
played a game against the AI. 
Although that AI met the conditions for having the most roads he didn't receive the longest road icon, or the two victory points that come with it... (this could be that you implemented longest road rather than most roads, wasn't sure. If that's the case then this isn't a problem)

**Comment by DallonTG** [comment]
The most roads/longest road isn't implemented until the server phase. We are all using the TA server, which implemented longest road. So this isn't a bug.
