### ISSUE TITLE
Finish turn error

### ISSUE THREAD

**Issue by jjwilbur** [thyer/CS340winter2016#224]
When your turn is done you can push finish turn multiple times quickly and in the comment history it doesn't say that you rolled.

**Comment by thyer** [comment]
Does finishing your turn mean you're supposed to roll immediately after? Or the other person doesn't get their thing logged in the chat history?

**Comment by jakebrucebrewer** [comment]
@jvansteeter Is this another server thing?

**Comment by jjwilbur** [comment]
I think you just need to disable the finish turn button as soon as push it. That way you can't press it again after you push it the first time. (Possible fix)

**Comment by jakebrucebrewer** [comment]
@jjwilbur that's a simple fix. Thank you for that suggestion! You rock!

**Comment by jakebrucebrewer** [comment]
@jjwilbur I'm poking around in the view and can't find where I would enable or disable that. Would you mind giving me another hint?

**Comment by jjwilbur** [comment]
@jakebrucebrewer Umm, I think it's in the turntracker when you call updateGameState(). You can say if the button is enabled or not. So I guess in the endTurn function you would change the message on the button and set enable to false.

**Comment by jakebrucebrewer** [comment]
@jjwilbur Thanks You're awesome. I just fixed it.
