### ISSUE TITLE
Test button?

### ISSUE THREAD

**Issue by jjwilbur** [thyer/CS340winter2016#225]
The test button still appears at the bottom of the client. Not sure if this is a bug or not.

**Comment by jakebrucebrewer** [comment]
@jjwilbur TA's told us to not worry about this.

**Comment by jjwilbur** [comment]
Oh my bad. Sorry i didn't realize!

**Comment by thyer** [comment]
That's correct, the test button is just an artifact and since you're only supposed to worry about Controllers, we're not holding you responsible for the sins of your progenitors. Closing bug as invalid.
