### ISSUE TITLE
Game doesn't finish ( Final game modal ... ?)

### ISSUE THREAD

**Issue by jjwilbur** [thyer/CS340winter2016#227]
When you win the game you can still keep playing. I believe it is supposed to redirect you to the games list and if you rejoin it pops up the winner window and then continually will just send you back to the game list.

**Comment by jakebrucebrewer** [comment]
@jjwilbur , Trent told us that as long as the game ends gracefully it is not a problem. Continuing to play is an option. @thyer

**Comment by thyer** [comment]
@jakebrucebrewer Continuing to play is NOT an option. That isn't graceful ending, it's a silent failure. You need to pop up the end game modal and announce that the game is over. If a player exits, then rejoins, you should also pop up the modal announcing the end of the game. Marking as a P4.
