### ISSUE TITLE
Road Build error

### ISSUE THREAD

**Issue by jjwilbur** [thyer/CS340winter2016#229]
When using road builder, you can place the second road on the same place as you placed the first road. Because of this you must not save that position when the first is placed, because you can't build on the first road you placed either.  
For example if I try to place two roads using the road builder card I X---Y----Z is the path I want to place.  I can place the first from X---Y.  But on the second one the road appears to be on X---Y, but you can't place the second road from Y----Z.

**Comment by jakebrucebrewer** [comment]
@jjwilbur I'm having a hard time visualizing the X Y thing. A screenshot would be helpful. Thanks.

**Comment by jjwilbur** [comment]
@jakebrucebrewer I'll try to get a screen shot for you. The basic idea is that you place your first road just fine, but then you can't place your second road off of your first one that you placed.

**Comment by thyer** [comment]
I believe that this isn't really a duplicate. They're both caused by the same underlying issue, but this issue says you can't place two roads sequentially during road building and the other issue says that both roads can be placed at the same location.
