### ISSUE TITLE
Bank never out of resources

### ISSUE THREAD

**Issue by kking937** [thyer/CS340winter2016#230]
If a bank is out of resource cards, a player can still maritime trade with the bank to have more than 19 of the same resource.  The limit is 19.

**Comment by cmriboldi** [comment]
This is an issue with the server not our code.

**Comment by kking937** [comment]
The server returns the number of resources that the bank has left in the JSON, and that should be stored in the model for reference.

**Comment by thyer** [comment]
Definitely a client issue.

**Comment by cmriboldi** [comment]
I fixed this issue. However, I am seeing that the server gives the bank 24 resources to start with not 19. So when testing that this bug is fixed you need to make sure that all players have a cumulative of 24 resources total, then the bank is empty.
