### ISSUE TITLE
Discard Cards

### ISSUE THREAD

**Issue by kking937** [thyer/CS340winter2016#232]
When a seven is rolled with 2+ clients and they need to discard (7+ in hand), 1 client will have the discard show up while the other client is waiting.  Once the 1st client has discarded, then the 2nd client will have the discard show.  Should be do synchronously.

**Comment by jakebrucebrewer** [comment]
@jvansteeter Is this a server issue? @jpp46

**Comment by thyer** [comment]
Marking this as a P5 because I'm not certain that it's requisite to happen this way (i.e. not incorrect behavior per definition), but you really ought to fix it.

**Comment by jpp46** [comment]
@kking937 @thyer 
This is another bug I cannot replicate, I did it with 2 clients as directed, but whenever the discard model is supposed to come up it does for both people paying provided they both have more than 7 cards. Again I am not sure what to do since I cannot replicate the bug?

**Comment by jakebrucebrewer** [comment]
@thyer Hey Trent. I'm pretty sure that we decided that this one should be marked as invalid since it can't be replicated. It's also not marked as fixed. So I just wanted to double check with you that we're not loosing points on this one.

**Comment by thyer** [comment]
Closing as invalid - I couldn't duplicate it in the original turned-in code
