### ISSUE TITLE
Can register with a password that is too short

### ISSUE THREAD

**Issue by el3ment** [thyer/CS340winter2016#233]
A user will be registered with a password that is too short.

**Comment by DallonTG** [comment]
This is just a comment for us when we fix it. Hidden in the general overview specs is this requirement:

> Registering a new user should reject the registration if the username is fewer than 3 or greater than
> seven characters, if the password is less than 5 characters long or is not made of allowed characters
> (alphanumerics, underscores, hyphens, or if the password verification entry doesn’t match the original.
