### ISSUE TITLE
Domestic Trading

### ISSUE THREAD

**Issue by kking937** [thyer/CS340winter2016#234]
If in domestic trade you set what you want to receive, then set what you will give, the trade button will be enabled.  But if you put what you will give back to 0, the button will change its text, but you can still send the trade.  So I can offer a trade without sending any resources.

**Comment by thyer** [comment]
@kking937 This is perfectly allowable, as far as I'm aware. Is there anything in the rules that prevents you from turning to your buddy and saying, "Gimme a sheep before something happens to that nice little vertex you've been trying to reach."
