### ISSUE TITLE
Team 4: Knight Card Does Start Move Robber Dialog

### ISSUE THREAD

**Issue by wesleyackerman** [thyer/CS340winter2016#235]
After multiple rounds, a player bought a development card which was a Knight. On the following turn, I clicked the Knight card in the development card view (The count of Knight cards was correct, at 1). The view closed, but no "Move Robber" action occurred. When I opened the card view again, the Knight card count was still one.

**Comment by eaglewyng** [comment]
I don't think we implemented the knight development card just yet. Was it filled out as done in our rubric?

**Comment by eaglewyng** [comment]
Labeling as invalid for points as we did not mark this as finished on the rubric, but we WILL fix this. Thanks for the heads up.

**Comment by thyer** [comment]
Closing, since you indicate you weren't going for implementation points on Knight when you sent it out for testing.
