### ISSUE TITLE
Team 13 - build road in two different locations

### ISSUE THREAD

**Issue by jrwalther** [thyer/CS340winter2016#236]
![tworoads](https://cloud.githubusercontent.com/assets/16724295/13482375/0d6e1f02-e0aa-11e5-8e36-734d55d3888e.png)

I can leave the game after I have built a road. Logging back in, that road is still there and the client wants me to build that same road again

**Comment by jrwalther** [comment]
This is a pretty freaking awesome bug. I have longest road now and nobody else has placed settlements

**Comment by bbarney7** [comment]
Yeah that's how the demo client works btw

**Comment by mcrowder65** [comment]
This bug is also in their client - please label your bugs dude
