### ISSUE TITLE
Invalid Points Value (Points code ... ?)

### ISSUE THREAD

**Issue by kking937** [thyer/CS340winter2016#237]
If at 9 points and you get 2 more points in one round, you then will have 11 points, but that throws an invalid points exception.  This is not caught or handled in any way causing the error to never stop the game and act in a weird way.

**Comment by jakebrucebrewer** [comment]
@cmriboldi Do you think that has to do with the "Finish Game" code that you wrote?

**Comment by jakebrucebrewer** [comment]
@kking937 Are you saying that you spotted the exception in the terminal log but it simply didn't end the game?
