### ISSUE TITLE
Team 13 - Multiple clients up

### ISSUE THREAD

**Issue by joshuahaertel** [thyer/CS340winter2016#239]
If the same user opens up two different client windows and logs into the same game, and chooses two different colors, the turn tracker will not display the most recent color chosen.

![screen shot 2016-03-02 at 7 18 06 pm](https://cloud.githubusercontent.com/assets/16691565/13482620/8f635f1c-e0ab-11e5-9825-96aa450de562.png)

**Comment by mcrowder65** [comment]
please label your bugs - sorry for the invalid tag

**Comment by joshuahaertel** [comment]
No worries. We're not getting the option to place any labels on our posts. I'm not sure why.

**Comment by menyx02** [comment]
You can't use the labels because you didn't email the TA's to be added as a contributor.

**Comment by joshuahaertel** [comment]
In a more realistic case:
1. Load up two different players in two different windows and have them join the same game.
2. Have one player exit the window and then come back in as a different color.
3. Only chat is updated in color while the turn tracker remains the same.

screenshot before:
![screen shot 2016-03-02 at 10 26 18 pm](https://cloud.githubusercontent.com/assets/16691565/13485588/b6dea6d0-e0c6-11e5-8dcd-d802863f38f3.png)
(refer to #367 for explanation of why they were both initially green)

screenshot after:
![screen shot 2016-03-02 at 10 29 35 pm](https://cloud.githubusercontent.com/assets/16691565/13485591/bea81072-e0c6-11e5-9655-a7c34e62f67b.png)

**Comment by mcrowder65** [comment]
Although this is a "bug" it's actually not our fault - I talked with bentz the other day and he said were fine.  Just so you know.

**Comment by mcrowder65** [comment]
marked invalid after further discussion with bentz.
