### ISSUE TITLE
Team 4: Two Points Added to Wrong Player on Longest Road

### ISSUE THREAD

**Issue by wesleyackerman** [thyer/CS340winter2016#241]
Player three added another road, giving them a road of length five. They were rightfully given 2 extra points and the longest road icon. However, Player four also had two points added to their score. Player four only had two settlements, and nothing else to give them victory points.

**Comment by eaglewyng** [comment]
Gotta make the game competitive somehow :D We'll look into it, thanks.

**Comment by matthewfcarlson** [comment]
This has been fixed!
