### ISSUE TITLE
Team 13 - closing/reopening trade

### ISSUE THREAD

**Issue by jrwalther** [thyer/CS340winter2016#242]
![weirdtrade](https://cloud.githubusercontent.com/assets/16724295/13482819/9aa74040-e0ac-11e5-9b6b-958b8e3269cc.png)
This trade is bad - only 1 wood 1 brick is being offered.
To replicate - close client while in receive trade and reopen

**Comment by mcrowder65** [comment]
Changed the severity to P4 because all it does is show the view differently when the client rejoins, the player still receives/sends the correct resources.
