### ISSUE TITLE
Team 13 - Create game

### ISSUE THREAD

**Issue by joshuahaertel** [thyer/CS340winter2016#245]
Client allows you to create a game without a name

**Comment by mcrowder65** [comment]
@joshuahaertel could you provide the specification on where we need to disallow empty games?

**Comment by joshuahaertel** [comment]
![null games1](https://cloud.githubusercontent.com/assets/16691565/13504027/cfee96ee-e12f-11e5-9312-a0facb228c47.png)

**Comment by mcrowder65** [comment]
Pre-conditions: name != null 
This spec confirms that this is an invalid bug.

**Comment by mcrowder65** [comment]
Please close this bug when you get the chance.

**Comment by joshuahaertel** [comment]
I suppose there is ambiguity in the spec, but since it is coming into the server as a JSON I would assume that name != null means that it cannot be an empty string. I may be wrong in my assumptions though, so ultimately it is up to the TA to clarify the confusion.

**Comment by mcrowder65** [comment]
calling .equals on a String in java will give you a null pointer exception.  Calling .equals on an empty string will allow you to compare it to other Strings.  There is a huge difference between null and empty - i don't see any ambiguity in the spec.

**Comment by joshuahaertel** [comment]
I can see your point of view, but again, we're looking at the JSON
communication, in which case I interpret null to mean empty. Again, the TAs
will have to clarify what is actually meant by the spec. If they say that
your assumptions are correct then I will gladly mark it as closed.
Regardless, I would not normally expect a game without a name to be created.

**Comment by mcrowder65** [comment]
sounds good
