### ISSUE TITLE
Team 2 - Can't add AIs

### ISSUE THREAD

**Issue by jakebrucebrewer** [thyer/CS340winter2016#248]
Team 2 Bug: 
Whenever you try to add AIs it just quits out of the menu and doesn't add an AI.

**Comment by emeraldarcher** [comment]
Phase 2 spec doesn't require AI players.

**Comment by jakebrucebrewer** [comment]
Gotcha. Cool.

**Comment by thyer** [comment]
@emeraldarcher Could you guys conceivably disable the AddAI button? I do have to mark this as a valid issue since you've left in a button that breaks stuff.

**Comment by thyer** [comment]
Duplicate of #299
