### ISSUE TITLE
Multiple Dev Cards

### ISSUE THREAD

**Issue by nevans224** [thyer/CS340winter2016#249]
After I own one soldier who is active, after I buy a second one I can't play either even though one should be available to me. Both are greyed out.
<img width="282" alt="devcards" src="https://cloud.githubusercontent.com/assets/11450031/13483362/dee28c2a-e0b0-11e5-9aa1-95426d73e36e.PNG">

**Comment by hunterrees** [comment]
@nevans224 Do you have any other details about the circumstances? We had a soldier from a previous turn and it was enabled, we bought another soldier and it still showed the soldier as enabled (the one from the previous turn). We then played the soldier and then all the dev cards were disabled (as they should be for that turn).

**Comment by nevans224** [comment]
@hunterrees I don't remember how I did this. If you tried to do it and couldn't reproduce it, go ahead and close this.
