### ISSUE TITLE
Choose Color Modal is never closed

### ISSUE THREAD

**Issue by verdude** [thyer/CS340winter2016#250]
After I place a road, the place road modal closes briefly and the select color modal is still there. It doesn't work but I can click on the cancel button and that takes me back to the join games modal which doesn't let me re-join that game that I was just in.

**Comment by verdude** [comment]
I can also create new games after I click cancel on the select color modal. I can click join but they just take me back to the game I was in.

**Comment by dro248** [comment]
@verdude : Shouldn't this have a P2 tag?
