### ISSUE TITLE
Finish button not updating correctly (clarification..)

### ISSUE THREAD

**Issue by byurfl** [thyer/CS340winter2016#254]
When the dice rolling and the discarding modal views first pop up, the button at the bottom of the screen should be disabled and should say something about "roll the dice"/"discard cards".

Instead, it is disabled and says "waiting for other players".

**Comment by thyer** [comment]
@byurfl Do you mean that the "roll the dice" button should be enabled or disabled?

**Comment by jakebrucebrewer** [comment]
@byurfl A screenshot would be helpful.

**Comment by byurfl** [comment]
Sorry, this got lost in a flood of notifications. Here's a screenshot:


![diceissue](https://cloud.githubusercontent.com/assets/17560567/13544891/363dd350-e23a-11e5-938f-5b55a05dd5e0.PNG)
