### ISSUE TITLE
Roll Controller

### ISSUE THREAD

**Issue by kamenomagic** [thyer/CS340winter2016#259]
The roll didn't come up on the second player. I rolled as the first player and then logged in as the second player and it didn't pop up. I got stuck because it said roll dice but didn't have a modal.
It only showed up on the first player, but it was noted that it shouldn't come up for the current implementation.

**Comment by dro248** [comment]
@kamenomagic : I have bumped this issue up to a P2 as it blocks gameplay. I recommend that the P4 tag be removed.
