### ISSUE TITLE
Rejoining will crash or cause odd behavior - occasionally

### ISSUE THREAD

**Issue by mcrowder65** [thyer/CS340winter2016#26]
Description: when rejoining a game, the game can freeze up, it can hide the bottom left turn tracker, sometimes it will hide your resources, you can roll and it won't let you end your turn.

Reproduce: Exit and game and rejoin it

**Comment by thyer** [comment]
This is blocking gameplay, but not bringing down the whole client. Keeping the P2 tag to reflect that.
