### ISSUE TITLE
Quickly clicking Finish Turn finishes other players' turns

### ISSUE THREAD

**Issue by byurfl** [thyer/CS340winter2016#272]
Steps to reproduce:
1. Start a game of Catan. It is easiest to see the behavior with 4 human players in the game.
2. Go through the setup phase (if necessary).
3. While the Finish Turn button is enabled, click it as quickly as possible.
4 Look at the Game History. You will see several consecutive messages saying "[player]'s turn just ended", and more than one client may be showing the dice-rolling view.

**Comment by jakebrucebrewer** [comment]
@jvansteeter Does this have to do with the server code?

**Comment by thyer** [comment]
This and issue #331 are very likely related.

**Comment by jakebrucebrewer** [comment]
@jvansteeter I took care of this one. It's fixed already.

**Comment by thyer** [comment]
I'm gonna close this one as a duplicate
