### ISSUE TITLE
Player not automatically added to new game

### ISSUE THREAD

**Issue by byurfl** [thyer/CS340winter2016#275]
When you create a game, you are not automatically added to the game.
In the demo client, creating a new game also adds you to that game.

Steps to reproduce:
1. Log in.
2. Create a new game.

**Comment by jakebrucebrewer** [comment]
@thyer Would you consider this one a bug?

**Comment by byurfl** [comment]
Note that it is in the functional spec (though it's certainly not severe):

Pressing the “create new game” button will bring up an overlay that allows you to name it and choose settings for initializing the game board. These are optional random settings. If a random setting is not selected, the game should initialize with the default settings (see the official game rules). **Pressing the “create” button should create a game, which should then show up in the game hub as a new game with one player.**

**Comment by thyer** [comment]
I do consider this a bug and am marking it as a P4 since it's incorrect behavior that was specifically mentioned in the specification.

**Comment by jakebrucebrewer** [comment]
thanks for pointing that out @byurfl
