### ISSUE TITLE
Map View Displayed In Chat

### ISSUE THREAD

**Issue by nmspackman** [thyer/CS340winter2016#278]
With no chat messages in the view on an AI game, the map view was displayed inside the chat log.
![image](https://cloud.githubusercontent.com/assets/11526734/13483928/5740e8b0-e0b6-11e5-81ed-4fc25641c138.png)

**Comment by chrisranderson** [comment]
How does this affect gameplay?

**Comment by nmspackman** [comment]
Sorry, I miss labeled it. Thank you for letting me know.

**Comment by danielmhair** [comment]
This was in the client. This is a view problem. Talked to the TAs. Also, I think this should be invalid
