### ISSUE TITLE
Can "maroon" settlement during setup round 2 (Clayton)

### ISSUE THREAD

**Issue by byurfl** [thyer/CS340winter2016#282]
Steps to reproduce:
1. Create a new game, or join one that is still in setup round 1.
2. Place a settlement, then place a road next to it.
3. In round 2, place a settlement on the other side of the board, then place your second road next to your first settlement. The second settlement is effectively "marooned", having no road connected to it.

**Comment by ccondie** [comment]
![screen shot 2016-03-03 at 3 39 29 pm](https://cloud.githubusercontent.com/assets/14207741/13512170/57935064-e156-11e5-917d-0256f8f39134.png)

**Comment by jakebrucebrewer** [comment]
@ccondie I tried assigning this one to you (like I've done to everyone else with their respective issues) but for some reason github is not letting me do it with you.

**Comment by thyer** [comment]
Marking as P3, was tempted to mark as P4. Willing to be swayed during passoff if you can show that it never adversely affected gameplay.
