### ISSUE TITLE
Turn tracker not cleared properly

### ISSUE THREAD

**Issue by byurfl** [thyer/CS340winter2016#292]
As player's scores change, the new scores are written over the old ones (or vice versa, can't really tell). The result is unreadable. It seems like the Longest Road and Largest Army icons are also not displayed properly, though points are awarded for them.

Steps to reproduce:
1. Start or join a game.
2. Obtain longest road and/or largest army.
3. Score becomes garbled and unreadable, and LR/LA icons do not appear in the turn tracker. Restarting the client and rejoining the game causes the turn tracker to become readable until scores change again.

**Comment by jakebrucebrewer** [comment]
@thyer I've tried calling "initialize" instead of just "update" in the turn tracker to fix this issue but the numbers still look funny when the scores change. Can I get a hint of where to change this in the view that we were provided?

**Comment by thyer** [comment]
Also using this as a header for an issue I discovered -- TurnTracker doesn't update when I change colors mid-game. In order to reproduce this, I created a game as player 1, but didn't join when brought to GameJoin screen. I joined with three other plays, the game began, and then I went back to the first player and joined as Purple. All his settlements are purple, but the TurnTracker keeps him as red on everyone else's screen.

**Comment by bje43** [comment]
No you can only get points back for bugs that were discovered during testing. Similarly you don't get points taken off for bugs that are found after the testing period was over so it won't hurt you. I don't know why the other team is still logging bugs against you now that the testing phase is over.

**Comment by bje43** [comment]
Disregard my email. Just do whatever Trent says.

**Comment by thyer** [comment]
@bje43 This was an issue I discovered while verifying the earlier bug reported. 

@jakebrucebrewer You cannot earn points back on this. The reason being that when you fix issues, it's possible to break other things (or disable functionality to make the new thing work). The only rule I've held to is that I won't look for new bugs in the process. If I find something glaring while verifying what's been reported, that's different.
