### ISSUE TITLE
cannot place road in valid location

### ISSUE THREAD

**Issue by el3ment** [thyer/CS340winter2016#297]
![image](https://cloud.githubusercontent.com/assets/2135235/13484097/f4012150-e0b7-11e5-9724-945f0d4b21cd.png)

**Comment by calebtonkinson** [comment]
Are there any steps to reproduce this? I played the game through to the same point and was unable to reproduce the problem you were having.
![screen shot 2016-03-03 at 7 02 14 am](https://cloud.githubusercontent.com/assets/9069966/13497008/71e5659c-e110-11e5-972d-25be74a9037a.png)
