### ISSUE TITLE
Domestic trade is not resetting after cancelling.

### ISSUE THREAD

**Issue by mcrowder65** [thyer/CS340winter2016#30]
Description:
Extra names keep showing up after I cancelled it.
Reproduce: try a domestic trade then cancel it, then try again.
![file_000 2](https://cloud.githubusercontent.com/assets/10186520/13436056/a6feead6-df9a-11e5-998f-d5e4e2ef94d4.jpeg)

**Comment by nmspackman** [comment]
Same as #4

**Comment by mcrowder65** [comment]
Closed because it's a duplicate.
