### ISSUE TITLE
It freezes your computer

### ISSUE THREAD

**Issue by mikehermes** [thyer/CS340winter2016#300]
When in the Chat Messages, pass in a large text message. The computer gets frozen and you will never be able to "let it go" without using control + alt + del or Option + Command + esc to close the game and re-log in.
Step to replicate:
1. click "Chat Messages" button
2. pass in a large text message such as, a large paragraph. 
And then you will see your cursor icon is spinning.

**Comment by byurfl** [comment]
How large a paragraph are we talking? I just put in the Gettysburg address and the Declaration of Independence and neither one caused any problems. Can you send me the text you used?

**Comment by mikehermes** [comment]
The size of the text file is like a dictionary. This is more like we are doing stress testing on your program.

**Comment by thyer** [comment]
@mikehermes @byurfl Just tried to duplicate this problem in real life, also couldn't get all the way through the dictionary before all my friends left. 

But in all seriousness, good job to Mike for finding it, but we won't hold you responsible for it.

**Comment by mikehermes** [comment]
should I just close this issue? I think for long run, no body’s message will be as large as a dictionary file.

Mike Lo

**Comment by thyer** [comment]
I went ahead and closed it already.
