### ISSUE TITLE
Multiple Players, Same color

### ISSUE THREAD

**Issue by jvansteeter** [thyer/CS340winter2016#302]
Team 2 Phase 2
If two players are joining a game and get to the choose color modal at the same time, they can both join with the same color and will both be in the game with same color.

**Comment by emeraldarcher** [comment]
@jvansteeter How can this be prevented when utilizing a poller?

**Comment by thyer** [comment]
Can be solved by querying server before issuing command

**Comment by derekargueta** [comment]
Fix: If the second user selects the same color and tries to join the game, there will be a modal message view saying the color has already been taken by another player
