### ISSUE TITLE
Server down, login non responsive

### ISSUE THREAD

**Issue by jvansteeter** [thyer/CS340winter2016#304]
Team 2 Phase 2
If the server is down, when the client tries to login or register, the program does nothing.  There is no error message or dialog, you just click the button and nothing happens.  Seems a little counter intuitive, the client would have no way of knowing the problem was with the server and not with them.

**Comment by yeyyosing** [comment]
You're having problems if you aren't running the server?

**Comment by emeraldarcher** [comment]
Duplicate with #310. Phase 2 spec requires no error handling for server communication issues.

**Comment by thyer** [comment]
Closing as duplicate
