### ISSUE TITLE
Map update not automatic - Team 2

### ISSUE THREAD

**Issue by jakebrucebrewer** [thyer/CS340winter2016#306]
Update doesn’t work. After Pete placed his road and his settlement. Mark does not get updated automatically.  On Mark’s client it says that it is still Pete’s turn even though he has already finished his setup round. Mark is also not prompted to place his settlement and road automatically.
![screen shot 2016-03-02 at 8 00 29 pm]

(https://cloud.githubusercontent.com/assets/10167955/13484178/cd37f930-e0b8-11e5-84c7-088cfa9693d9.png)

**Comment by yeyyosing** [comment]
Does this happen every time? Can you reproduce this?

**Comment by emeraldarcher** [comment]
Did you create a new game @jakebrucebrewer  or is this one of the games that comes with the server?

**Comment by jakebrucebrewer** [comment]
@emeraldarcher @yeyyosing This doesn't happen every time, but it happened to several of the team members testing it in a random fashion. @yeyyosing it is reproducible, since it happened at least once every time I played. If you log out and then log back in then it usually solves the problem. @emeraldarcher I did create a new game.

**Comment by yeyyosing** [comment]
If I can't reproduce it every time by doing a specific set of moves to get there, then this shouldn't be logged as a bug.  Tell me exactly how to reproduce this bug and make it happen every time, so that I can fix this bug if it really is an issue.

**Comment by jakebrucebrewer** [comment]
Hey @yeyyosing and @emeraldarcher, can I get your advice? I'm trying to fix my turn tracker and when the point numbers get updated then the numbers look blotchy and sit on top of each other. We have no idea how to fix this but we remember that when we were testing your guys' code that the turn tracker worked perfectly. Would you mind explaining to me how you fixed the turn tracker or putting me in touch with your team member who handled that? Our team would really appreciate it. Thanks!

**Comment by jakebrucebrewer** [comment]
Nevermind -- @yeyyosing and @emeraldarcher, I just figured it out! Thanks anyways.
