### ISSUE TITLE
Discard modal resets prematurely

### ISSUE THREAD

**Issue by hydn** [thyer/CS340winter2016#31]
**Description**
During the discard phase, every player's discard modal will reset whenever another player discards.

**Steps to Reproduce**
1. Start multiplayer game
2. Have multiple players collect more than 7 cards
3. Roll a 7
4. All players increment their discard amounts
5. One player discards
6. Every other player's modals will reset to having 0 resources set for discard

**Comment by tclaw46** [comment]
Added a boolean to check if the player is already in the process of discarding. If so, the resourceList will not be reinitialized and the modal will not be reset.
