### ISSUE TITLE
Server down joining issues

### ISSUE THREAD

**Issue by jvansteeter** [thyer/CS340winter2016#310]
Team 2 Phase 2
If the server goes down while the client is joining a game, the modals simply close and the game sits there on an empty unpopulated map being non-responsive.  No indicator to let the client know that the problem is with the server and not the client.  This similar problem happens while on the Player Waiting modal, the program simply does nothing, which could lead to clients waiting indefinitely not knowing that no one will be joining the game.

**Comment by yeyyosing** [comment]
There's problems if the server goes down?

**Comment by emeraldarcher** [comment]
Phase 2 spec doesn't require handling server miscommunication errors such as this.

**Comment by derekargueta** [comment]
Fix: Any network operations will bring up a modal indicating the server is down.
