### ISSUE TITLE
New Game auto-joins as white

### ISSUE THREAD

**Issue by jvansteeter** [thyer/CS340winter2016#314]
Team 2 Phase 2
This is another one that the TAs may throw out as not a real bug, but I thought I'd post it anyway because this doesn't appear to operate the way I'd think it should.
When a player creates a new game, that player is automatically joined to that game as the color white, it returns you to the game selector modal so you can rejoin as another color, but without ever seeing the color selector you already assigned to that game as the white player.

**Comment by dannyharding10** [comment]
When creating a game, the player should be automatically added to the game. The only way to do this is by giving a color.  White was the most neutral option.

**Comment by jvansteeter** [comment]
Yeah, I didn't realize that you were supposed to automatically join the game when you create it.  This is not an issue and never should have been created, totally my bad.
