### ISSUE TITLE
Rolling a seven flashes some screens then crashes

### ISSUE THREAD

**Issue by jpp46** [thyer/CS340winter2016#317]
I rolled a seven the discard view came up, but before I could discard it closed, it was then frozen and never gave me the chance to rob.

**Comment by yeyyosing** [comment]
How do the issues #353 and #355 exist if this is an issue? Can you reproduce this?

**Comment by thyer** [comment]
Closing as invalid. @jpp46 we really need some more follow-up in order to diagnose these.
