### ISSUE TITLE
Username length requirements not enforced

### ISSUE THREAD

**Issue by byurfl** [thyer/CS340winter2016#324]
Usernames with fewer than 3 characters or more than 7 characters should not be allowed. If the user tries to register with an invalid username, the application should display an error message and return them to the login screen without adding the user.

Steps to reproduce:
1. Start the client.
2. On the "Register" side, enter a username with fewer than 3 characters or more than 7 characters.
3. Enter a valid password in the password fields.
4. Click "Register". Should display an error and return to login, but instead proceeds to the game list.

**Comment by jakebrucebrewer** [comment]
@jvansteeter I didn't know there was a username length requirement. Is there?
