### ISSUE TITLE
Round 2 Setup (Clayton)

### ISSUE THREAD

**Issue by kking937** [thyer/CS340winter2016#325]
On a two client set up as first and second players, after placing my second round setup, the pull up map didn't disappear telling me to place a settlement.

**Comment by jakebrucebrewer** [comment]
@kking937 is this reproducible?

**Comment by kking937** [comment]
I haven't been able to reproduce it.

**Comment by thyer** [comment]
Marking as invalid since tester can't provide steps for reproduction.
