### ISSUE TITLE
rolling seven breaks

### ISSUE THREAD

**Issue by jpp46** [thyer/CS340winter2016#330]
I rolled a 7, and it started to let me discard then rolled a 7 and then a 4 and then froze

**Comment by yeyyosing** [comment]
How do the issues #353 and #355 exist if this is an issue?

**Comment by thyer** [comment]
@jpp46 In general, it's nice to see concise descriptions, but you could definitely be a little more verbose in explaining these issues.

**Comment by thyer** [comment]
Closing as invalid
