### ISSUE TITLE
Roll Dice Showing on Multiple Clients

### ISSUE THREAD

**Issue by kking937** [thyer/CS340winter2016#331]
With 2+ clients, if one client clicks the finish turn button multiple times (4+), then both clients will have the roll dice modal appear on the screen.

**Comment by jakebrucebrewer** [comment]
@jvansteeter Does this have to do with server code? What's the best way of preventing this?

**Comment by thyer** [comment]
@kking937 Awesome bug! @jakebrucebrewer @cmriboldi We had a similar issue happen. If I can help diagnosing this, please let me know - we had a similar issue when I took the class and it was tricky to solve.

**Comment by jakebrucebrewer** [comment]
@cmriboldi Fixed this one.
