### ISSUE TITLE
Register with all blank fields seems to create a "valid" player

### ISSUE THREAD

**Issue by DanielSaunders** [thyer/CS340winter2016#332]
It appears that there is no check on the validity of the fields on the register player form. I could create a player with a blank username and password, and then log it with the same player.

**Comment by eaglewyng** [comment]
Verified as valid. We need to check for data validity: ie, the username should have [3:7] characters, and password length should be at least 5 chars and made of alphanumerics, underscores, and hyphens.

**Comment by matthewfcarlson** [comment]
Implemented as of last night
