### ISSUE TITLE
New game keeps reloading old game.

### ISSUE THREAD

**Issue by tclaw46** [thyer/CS340winter2016#333]
I quit out of a game during the set up phase after placing a settlement and road and started a new game. The old game kept getting loaded instead of a new game being started. Tried creating another new game. The same problem appeared.

![bug3](https://cloud.githubusercontent.com/assets/9815905/13484612/c3d04812-e0bc-11e5-90e8-409db4defd0a.PNG)

I got this error from that game.

**Comment by hunterrees** [comment]
@tclaw46 What do you mean by kept showing old game? Would it enter you into the old game even after restarting the client?

**Comment by thelaurence** [comment]
@hunterrees I'll try and get further clarification from @tclaw46.

**Comment by tclaw46** [comment]
I exited a game while in the middle of set up phase and restarted the client. I started a new game and for some reason the previous game that was still in the middle of set up phase kept reloading. I tried this a couple of times and it kept doing it. I did forget to mention that I had set the game to have random tiles and ports so its possible the error arose from that.
