### ISSUE TITLE
Discarding

### ISSUE THREAD

**Issue by kking937** [thyer/CS340winter2016#337]
On a 2 client setup, if both players have to discard, and the first player discards half of his hand, the discard box will keep appear.

**Comment by jakebrucebrewer** [comment]
@kking937 Is this reproducible?

**Comment by thyer** [comment]
I'm using this ticket as the header -- reproduced this by using AIs. Blocked all gameplay, and the discard state seemed really messed up. I won't mark this one as fixed, but also won't elevate to P2 since it wasn't labelled as such during testing.

**Comment by jakebrucebrewer** [comment]
@thyer Are you saying that just using AIs reproduces this bug? If so, then it is not reproducible on our end and we are still unclear on how to fix this. I personally used 1,2 and 3 AIs dozens of times to validate this bug and never ever ran into it once. I'm pretty sure my team members had a similar experience. @jpp46 Did you ever discover a pattern to reproduce this or see it at all?

**Comment by thyer** [comment]
I had this happen on my first try and when I repeated it the second time, it happened again. My steps were as follows:
1. Register as a new player, create game. Don't join, but wait in the lobby.
2. Register a second account as a new player. Join existing game as purple.
3. Join the first player to the game as yellow.
4. Add two AIs in the first player's console.
5. Continue playing until the AI rolls a 7. Never play anything, just continually collect resources. 
6. ?????
7. Profit.
