### ISSUE TITLE
Player does not join game just created

### ISSUE THREAD

**Issue by DanielSaunders** [thyer/CS340winter2016#340]
On the creation of a new game, the creating player does not get added to the game. Instead, the game lists no current players.

**Comment by eaglewyng** [comment]
More details: It seems in the spec the player should join the game immediately after creating it. The current version of our client does not seem to do this. Verified as a current issue.

**Comment by matthewfcarlson** [comment]
My apologies. I didn't realize that was part of the spec.

**Comment by matthewfcarlson** [comment]
Added to the game.
