### ISSUE TITLE
domestic trade buttons

### ISSUE THREAD

**Issue by ScottVaughan** [thyer/CS340winter2016#347]
The domestic trade window, it is suppose to create 4 buttons for each potential person to trade with. However, we noticed that the window seemed to recreate multiple buttons (as if it is stuck in a loop). It's important to note that this only happens a few times, it doesn’t happen on every user’s turn.

**Comment by dbitter2** [comment]
fixed

**Comment by Sicilica** [comment]
Probably a P5 bug, as the buttons simply got newly created each time the dialog was opened and never got cleaned up. They should still have functioned normally.
