### ISSUE TITLE
Robbing error

### ISSUE THREAD

**Issue by airhop** [thyer/CS340winter2016#349]
Sometimes after moving a robber, not allowing you to finish your turn unless you close the screen and log back in

**Comment by kking937** [comment]
Trying to reproduce this error, and I cannot do it.  Can you please go in more detail telling how you were able to get this to happen?

**Comment by thyer** [comment]
Will attempt to dupe during TA testing

**Comment by thyer** [comment]
Closing as invalid. Couldn't dupe during testing
