### ISSUE TITLE
Setup Stage issues

### ISSUE THREAD

**Issue by DanielSaunders** [thyer/CS340winter2016#350]
It is hard to pin point exactly what the issue seems to be, or how many bugs might be interacting.

I started up two clients and had them join a new game. Then I added two AI players. There seem to be a variety of issues related to the setup phase - the behavior is just unpredictable. They generally end with a blocked game. Both clients say, "Waiting for other players," and no other actions are possible. One client placed one settlement and no road. The other client was able to place a road and a settlement. Neither client has the setup-phase map open anymore.

I had one case where both clients showed the setup-phase map as soon as the game started and allowed both players to setup at the same time. Once one finished, the other was not able to finish, and the game blocked.

**Comment by DanielSaunders** [comment]
Here was the debug output from the two clients:
Client 1:
```
Offer: null        
 
--------------------- Refresh: 12 -------------------------   
Offer: null            
          
--------------------- Refresh: 13 ------------------------- 
Offer: null 
     
--------------------- Refresh: 14 ------------------------- 
Notify Center for MAP = 1
Notify Center for SCORE = 2 
Refreshing game history... 
Notify Center for LOG = 1 
Offer: null       
     
--------------------- Refresh: 15 -------------------------
Refreshing game history... 
Notify Center for LOG = 1
Offer: null
 
--------------------- Refresh: 16 -------------------------     
STATE Refreshed to FIRSTROUND current player:1  
Old TS: FIRST_ROUND_MY_TURN New: FIRST_ROUND_WAITING    
Player index in alert: 0    
Other: -2    
Truth Value: false         
Map controller handling state: FIRST_ROUND_WAITING     
Notify Center for STATE = 8  
Refreshing game history... 
Notify Center for LOG = 1
Offer: null 
Wasn't able to update
 ```

Client 2:
```
Offer: null

--------------------- Refresh: 5 -------------------------
Offer: null

--------------------- Refresh: 6 -------------------------
Offer: null

--------------------- Refresh: 7 -------------------------
Offer: null

--------------------- Refresh: 8 -------------------------
Offer: null

--------------------- Refresh: 9 -------------------------
Offer: null

--------------------- Refresh: 10 -------------------------
Notify Center for MAP = 1
Notify Center for SCORE = 2
Refreshing game history...
Notify Center for LOG = 1
Offer: null

--------------------- Refresh: 12 -------------------------
STATE Refreshed to FIRSTROUND current player:1
Old TS: FIRST_ROUND_MY_TURN New: FIRST_ROUND_WAITING
Map controller handling state: FIRST_ROUND_WAITING
Player index in alert: 0
Other: -2
Truth Value: false
Notify Center for STATE = 8
Notify Center for MAP = 1
Notify Center for SCORE = 2
Refreshing game history...
Notify Center for LOG = 1
Offer: null
```

**Comment by tunadude09** [comment]
DanielSaunders, what is so computer setup like? OS? Hardware? Etc?  I'm just asking because I'm the only one out of our entire group whose has been able reproduce this bug. It almost always happens to me WHEN it try to set up two players locally.. it almost never works... but literally everyone else in our group has been able to play the game without ever seeing this bug. John and I are wondering if this is a hardware related issue? Please let us know what environment you're in, thanks

**Comment by eaglewyng** [comment]
I think the priority of this bug should be less because none of us are able to reproduce it. It seems to be intermittent or hardware dependent.

**Comment by sadler-j** [comment]
This issue has been fixed (in that it now works on @tunadude09's computer). No idea as to why it is computer specific.

**Comment by thyer** [comment]
@sadler-j @eaglewyng I'll knock down the priority on this when we meet. If you figure out why it was hardware-specific, I'd be interested in finding out.

**Comment by thyer** [comment]
Marking down to P5 since it's so hard to dupe. Will bump it up to a P4 if I can dupe during testing
