### ISSUE TITLE
Can rob self

### ISSUE THREAD

**Issue by jpp46** [thyer/CS340winter2016#353]
<img width="1321" alt="screen shot 2016-03-02 at 9 42 05 pm" src="https://cloud.githubusercontent.com/assets/11218420/13484934/ae392af2-e0bf-11e5-8324-50bb5631176f.png">

**Comment by yeyyosing** [comment]
the only way to move the robber with the server that they gave us is the rob player method. So you have to rob somebody. How else can you go about his problem?

**Comment by thyer** [comment]
Not a bug, at the very most, we could call it a stylistic thing, but this is a little to picky to justify taking away points.
