### ISSUE TITLE
Robbed myself, automatic

### ISSUE THREAD

**Issue by jpp46** [thyer/CS340winter2016#355]
I put the robber on a spot with no settlements/cities and the history read that I had robbed myself
<img width="1108" alt="screen shot 2016-03-02 at 9 43 40 pm" src="https://cloud.githubusercontent.com/assets/11218420/13484954/f6aa7606-e0bf-11e5-9105-e3acd288dece.png">

**Comment by yeyyosing** [comment]
the only way to move the robber with the server that they gave us is the rob player method.  So you have to rob somebody.  How else can you go about his problem?

**Comment by thyer** [comment]
Same as other issue. Not a bug.
