### ISSUE TITLE
Double Robbing

### ISSUE THREAD

**Issue by byurfl** [thyer/CS340winter2016#360]
When you roll a 7, the robber view comes up twice. The second time seems to sometimes (but not always) cost you a soldier card, even if you don't have any.

Steps to reproduce:
1. Roll a 7, discard if you have to.
2. Place the robber and (optionally) steal a card.
3. Place the robber again and (optionally) steal a card. This might cost a soldier card, but apparently doesn't _always_ cost a soldier card.

**Comment by thyer** [comment]
Verified fixed
