### ISSUE TITLE
Errant "Add Computer Player" dialog

### ISSUE THREAD

**Issue by panzertime** [thyer/CS340winter2016#362]
Reproduce:
- Begin new game with AI players
- Finish game and get returned to the home screen
- Rejoin a game (where it is your turn, possibly)
Expected behavior:
You are returned to a complete Map, History, etc. and the Roll View appears

Actual behavior:
As the game loads the state, the "ADD COMPUTER PLAYER" dialog from the previous game displays

This may be possible to reproduce in other ways, such as by beginning a new game and then canceling it while adding AI players.

**Comment by mcrowder65** [comment]
Could you please provide pictures with this or something? I just tried this with the exact reproduce steps and could not reproduce it. @panzertime
