### ISSUE TITLE
Strange Color Selection behavior

### ISSUE THREAD

**Issue by joshuahaertel** [thyer/CS340winter2016#370]
1. Open up two clients
2. Have one of them create a game and then go to join it without selecting a color yet
3. Have the other go to join that game, select a color and hit Join Game (Red is disabled, but I understand it's the default sent to the sever)
4. Instead of the color being disabled, the other client will get kicked out of the color option menu

**Comment by joshuahaertel** [comment]
Additionally, if one of the client players is selecting his color and the other client, different player, creates a game then the first one gets kicked out of the color selection mode

**Comment by joshuahaertel** [comment]
Possibly a P4 or P2, it depends how many clients you expect to be creating new games that kick other clients out of the color selection modal.

**Comment by mcrowder65** [comment]
I don't think it's a p3, yes, i agree it's annoying but the actual gameplay itself, no - you're not in the game yet.

**Comment by thyer** [comment]
Marking as a P5 since this isn't incorrect behavior, more a thing of convenience.

**Comment by bbarney7** [comment]
Talked to Bentz - said this is invalid
