### ISSUE TITLE
Cannot move robber to an empty hex

### ISSUE THREAD

**Issue by yatteau** [thyer/CS340winter2016#372]
Moving the robber to a hex where no player has a settlement or city displays the "Choose who to Rob" dialogue, with an "OK" button for the only option of "None". Clicking the button returns the game to the "Move the Robber!" screen where the player can place the robber somewhere else. The player should be able to place the robber on a hex and rob no one if there are no other player cities or settlements adjacent to that hex. The behavior for placing the robber on an empty hex that the robber is already on is the same, but this is covered by another bug, so is not included in the scope of this issue.

**Comment by eaglewyng** [comment]
Verified as valid. Thanks!

**Comment by thyer** [comment]
Marking as P3, was torn between P3 and P4. Open to further input
