### ISSUE TITLE
robber does not show up until after first road is placed in setup phase.

### ISSUE THREAD

**Issue by jmbarzee** [thyer/CS340winter2016#373]
1) start a game
2) join the game
3) add the robots
4) see no robber
5) place settlement
6) see robber

**Comment by mcrowder65** [comment]
how does this affect gameplay? it's also a duplicate.

**Comment by jmbarzee** [comment]
good call, just searched setup and figured I would find others. You should link them!

**Comment by mcrowder65** [comment]
Changed to p4 because it's incorrect behavior - it affects gameplay in no way, just the way you're looking at the board for like ~20 seconds.  Also it's a duplicate.

**Comment by thyer** [comment]
Closing duplicate
