### ISSUE TITLE
Game History is sporadic

### ISSUE THREAD

**Issue by KasiKarra** [thyer/CS340winter2016#378]
Game History is sporadic on updating.  Sometimes it updates regularly and other times it take 3 human turns to get there.

**Comment by jtmingus** [comment]
@KasiKarra Was there anything specific that caused in to be sporadic? I've been trying to re-create the issue, but I can't seem to do it.

**Comment by KasiKarra** [comment]
It was like the poller wasn't updating it, but that it was waiting for the player's turn to update itself so it would go for long periods of time without telling about anything that other players did.

**Comment by thyer** [comment]
Marking as a P5, will try to duplicate during TA testing.
