### ISSUE TITLE
Can't place robber when playing soldier card

### ISSUE THREAD

**Issue by hunterrees** [thyer/CS340winter2016#38]
When I try to play the soldier card, it doesn't allow me to place the robber anywhere (I also can't cancel placing the robber)

**Comment by hunterrees** [comment]
![thumb_img_0544_1024](https://cloud.githubusercontent.com/assets/16613772/13473034/c860c4a8-e074-11e5-916b-419428d6af9c.jpg)

**Comment by panzertime** [comment]
I didn't have this problem on Monday.  Anyone else seeing it?
