### ISSUE TITLE
TurnTracker update

### ISSUE THREAD

**Issue by KasiKarra** [thyer/CS340winter2016#380]
Turn Tracker doesn't update during the setup phase like the "ant client" version does

**Comment by kking937** [comment]
Can you clarify? What doesn't get updated?

**Comment by KasiKarra** [comment]
During the setup phase the points recieved are not updated.  It isn't until the start of the game that the points update.  Also the colors do not update if another player logs out and changes colors unless the current player does so as well.

**Comment by thyer** [comment]
Marking as P5. It's probably incorrect behavior, but I can't find anything specific enough in the specs to elevate to a P4.
