### ISSUE TITLE
Rolling a 7

### ISSUE THREAD

**Issue by KasiKarra** [thyer/CS340winter2016#381]
Rolling a 7 does activate the robber, but it doesn't say that you rolled a 7 with the roll result pop up window, it just goes straight to moving the robber

**Comment by byurfl** [comment]
Marked as valid and fixed. I would argue this should be a P5 at worst, since if you roll the dice and then have to move the robber it's implied that you rolled a 7.

**Comment by thyer** [comment]
@byurfl You're right. Marking as P5.
