### ISSUE TITLE
Cannot place settlement when I should be able to

### ISSUE THREAD

**Issue by danielmhair** [thyer/CS340winter2016#387]
cannot place a settlement as show in the image below

![upload_3_2_2016_at_4_19_02_pm](https://cloud.githubusercontent.com/assets/7373734/13486454/8b107bd4-e0ce-11e5-9500-8b7c22f86893.png)

**Comment by calebtonkinson** [comment]
Are there any steps to reproduce? I created a game and then played through until I was in essentially the exact same setup and I did not receive that error.
![screen shot 2016-03-03 at 6 45 48 am](https://cloud.githubusercontent.com/assets/9069966/13496904/f8db0be8-e10f-11e5-891d-c8378dee93ef.png)
