### ISSUE TITLE
Login as a registered user, Join game, add AI's and setup doesn't appear.

### ISSUE THREAD

**Issue by skysearcher** [thyer/CS340winter2016#391]

**Comment by byurfl** [comment]
Same problem as #397.

**Comment by KasiKarra** [comment]
Fyi the bugs are similar, but not quite the same.  397 says register as a user and attempt to create a game and join.  This one is saying to Login as a user that has been registered and attempt the same thing.

**Comment by byurfl** [comment]
That's fair. Removing the duplicate label.

**Comment by thyer** [comment]
I'm going to consider #397 and this the same issue, but will elevate this issue to a P2 since it prevented the game from being played.
