### ISSUE TITLE
Inconsistent dings

### ISSUE THREAD

**Issue by yatteau** [thyer/CS340winter2016#393]
The game makes a noise after adding a first and a third computer player, but not after adding the second. This obviously isn't the most important bug, but if you include sounds they should be predictable, otherwise users may get confused about their meaning.

**Comment by eaglewyng** [comment]
Thanks for letting us know. The first ding notifies that he has joined the game, and the second ding notifies the user that the game is starting--it doesn't have anything to do with the AI. As this is an extra feature and it works as designed, I'm marking this as invalid. However, you do have a good point--maybe something we'll do in the future is to ONLY have the game ding when someone chats.

**Comment by thyer** [comment]
Offering @eaglewyng extra credit if he can replace the ding with an audio clip from "Welcome to the Jungle"
