### ISSUE TITLE
Domestic Trade buttons added multiple times

### ISSUE THREAD

**Issue by seattleite7** [thyer/CS340winter2016#4]
Description: The domestic trade buttons that select who you want to make a trade with are created multiple times.

Steps to reproduce:
Open domestic trade
Select cancel
Open domestic trade again

Screenshots:
![c1](https://cloud.githubusercontent.com/assets/10567483/13431216/b8120cf0-df85-11e5-9a48-55a4bcb69e8e.png)
![c2](https://cloud.githubusercontent.com/assets/10567483/13431220/bcfb7742-df85-11e5-8fdf-e76a15424f90.PNG)

**Comment by nmspackman** [comment]
Same as #30
