### ISSUE TITLE
Occasionally can roll dice twice

### ISSUE THREAD

**Issue by calebtonkinson** [thyer/CS340winter2016#40]
**Description**
My dice rolled twice after clicking

**Steps to reproduce**
1. Start game
2. Go through setup
3. Double click the roll button until it happens

**Screenshots**
![screen shot 2016-03-01 at 8 46 34 am](https://cloud.githubusercontent.com/assets/9069966/13442011/85130386-dfb7-11e5-8e8e-27db992a2430.png)

**Comment by thelaurence** [comment]
Duplicate/same cause as #32
