### ISSUE TITLE
Monuments Play one at a time

### ISSUE THREAD

**Issue by jmbarzee** [thyer/CS340winter2016#403]
It is reasonable to not require play each monument individually because the rules say "You only reveal Victory Point Cards when the game is over." I can play monuments while having enough to finish the game, but not actually finishing it.  ie 8pts -> 9pts with another monument in hand

**Comment by seattleite7** [comment]
Marked as invalid because TAs said monuments could be handled several ways, including this one... Steve can confirm

**Comment by thyer** [comment]
Duplicate
