### ISSUE TITLE
GUI scaling issues

### ISSUE THREAD

**Issue by yatteau** [thyer/CS340winter2016#404]
On some operating systems the login screen is not scaled properly, so that some of the text does not appear. This seems to only be an issue on Macs, and I'm not sure if it's something that's fixable (we have a similar issue with our client). But this is what I see when I start the client on my machine:
![screen shot 2016-03-02 at 11 40 58 pm](https://cloud.githubusercontent.com/assets/1462206/13486918/a74c54b8-e0d2-11e5-939e-4b3439421da3.png)

**Comment by eaglewyng** [comment]
I'm not 100% sure what to do about/with this one, since we really haven't talked about GUI scaling or developing for different platforms. I see what you're getting at though. I wouldn't like to see that on my Catan Client if I had a Mac.

**Comment by thyer** [comment]
This is a non-issue. Closing as invalid.
