### ISSUE TITLE
Monuments can be played before game end

### ISSUE THREAD

**Issue by jmbarzee** [thyer/CS340winter2016#405]
According to the rules "You only reveal Victory Point Cards when the game is over"

reproduce: 
1) new game - robots
2) buy dev cards until monument
3)  notice 8pts on board, 1pt in hand, can still play monument

**Comment by bbarney7** [comment]
How is this different than the problem you just logged???

**Comment by bbarney7** [comment]
Seems to be a duplicate to me

**Comment by seattleite7** [comment]
Marked as invalid because TAs said monuments could be handled several ways, including this one... Steve can confirm

**Comment by thyer** [comment]
Trent confirming that this isn't a bug
