### ISSUE TITLE
When robbing a player, their colors didn’t show up, just their names.

### ISSUE THREAD

**Issue by calebtonkinson** [thyer/CS340winter2016#41]
**Description**
When robbing players, the modal doesn't update properly, it just shows their name but not their color.

**Steps to reproduce**
1. Start game
2. Roll 7
3. Place robber on tile where some players have settlements

**Screenshots**

![screen shot 2016-03-01 at 8 38 04 am](https://cloud.githubusercontent.com/assets/9069966/13442171/18d584e0-dfb8-11e5-9b76-13dc520174bc.png)

**Comment by thelaurence** [comment]
Just ran the original .jar and got the following robbery modal:

![image](https://cloud.githubusercontent.com/assets/10649804/13580553/14f97582-e460-11e5-92ee-0fdbcb3aea1b.png)

It appears that in the screenshot in the original report the colors are being set correctly, but only on the edges of the player rectangles. Judging by the Game History/Chat tabs, this tester was running on a Mac. On our Windows and Linux machines the colors are as they should be.
