### ISSUE TITLE
Team 9 - Domestic trade does not set limits on how high you can increase the offer.

### ISSUE THREAD

**Issue by MDeBuse** [thyer/CS340winter2016#417]
When in the domestic trade view, the up arrows to not have any upper bounds. I don't know if this is because it has not been implemented, or whether or not it is because we have not started a game at this point so it doesn't have any idea what is in the player's hand.

**Comment by parsonsjo1** [comment]
I also made an issue for this, #429 I believe.

**Comment by dro248** [comment]
We didn't implement Domestic Trade. See implementation pdf bundled with zip file.
