### ISSUE TITLE
Team 9 - Maritime Trade not implemented

### ISSUE THREAD

**Issue by MDeBuse** [thyer/CS340winter2016#421]
When getting past the login screen (whether successfully or not) both domestic and maritime trade buttons show. The Domestic trade brings up the view, but the maritime does not. I don't know if they are visible for testing purposes or not.

**Comment by parsonsjo1** [comment]
I also found this to be an issue. I would give it a [P3 Incorrect behavior that affects gameplay]

**Comment by verdude** [comment]
It works when you have 4 resources of one kind and it is your turn. The model won't pop up otherwise. 

Still an issue though, because it probably should popup with all of the items grayed out if you don't have enough or if it isn't your turn.

**Comment by parsonsjo1** [comment]
Okay, great! I will test that out.

Here is what it should look like when it is not your turn or you do not have enough resources
![image](https://cloud.githubusercontent.com/assets/12648552/13518957/4a755e1a-e190-11e5-8045-8b78833fbc36.png)
