### ISSUE TITLE
Domestic Trade Button Display

### ISSUE THREAD

**Issue by parsonsjo1** [thyer/CS340winter2016#427]
The increase and decrease options for resources should not appear when none is selected.
The decrease option should not appear when no resources have been increased to be sent.
The increase option should appear when send or receive is selected.
The decrease option should appear when the increase option is greater than 0.

Incorrect Version
![image](https://cloud.githubusercontent.com/assets/12648552/13518445/276c90f0-e18b-11e5-8083-ed1c42da0bc7.png)

Correct initial version
![image](https://cloud.githubusercontent.com/assets/12648552/13518472/7bf0ad6e-e18b-11e5-8cfa-66c7f39c2cb0.png)

Correct option display
![image](https://cloud.githubusercontent.com/assets/12648552/13518513/02de5984-e18c-11e5-807c-7ce2dc242e30.png)

*Update* Increase and decrease buttons do disappear if none is selected again; just make that happen when the window is initially opened.

**Comment by dro248** [comment]
Marked invalid because we did not implement Domestic Trade. See implementation pdf included in zip file.
