### ISSUE TITLE
Domestic Trade Not Your Turn

### ISSUE THREAD

**Issue by parsonsjo1** [thyer/CS340winter2016#428]
The domestic trade should display no options and should have a grayed out box that says "not your turn" when it is not the player's turn

Incorrect display on off turn
![image](https://cloud.githubusercontent.com/assets/12648552/13518534/45267dc6-e18c-11e5-8aa5-424f089edc1c.png)

Correct display on off turn
![image](https://cloud.githubusercontent.com/assets/12648552/13518538/567e5c9c-e18c-11e5-97a4-200564642f7b.png)

**Comment by dro248** [comment]
Marked invalid because we did not implement Domestic Trade.
