### ISSUE TITLE
Domestic Trade Sending Resources Button Display

### ISSUE THREAD

**Issue by parsonsjo1** [thyer/CS340winter2016#429]
The player should not be able to send more resources than they have. The option to increase should disappear once the player reaches the maximum amount of resources that they currently have.

Incorrect display
![image](https://cloud.githubusercontent.com/assets/12648552/13518550/8885cbb2-e18c-11e5-94b7-8f4b145bf9c8.png)

Correct display
![image](https://cloud.githubusercontent.com/assets/12648552/13518565/a69fa802-e18c-11e5-9373-3473e7a8a855.png)

**Comment by dro248** [comment]
Marked invalid because we did not implement AI. See implementation pdf included in zip file.
