### ISSUE TITLE
Domestic Trade No Option to Select Player to Trade With

### ISSUE THREAD

**Issue by parsonsjo1** [thyer/CS340winter2016#430]
There is no option to select a player to trade with because they are not showing up; players to select from says none. Maybe it is because I picked the same color for all of the players, but I will have to try it again when everyone is different colors. Also, the game bar should update to "select a player" after setting the resources to trade.

Incorrect display
![image](https://cloud.githubusercontent.com/assets/12648552/13518637/65ec73d4-e18d-11e5-8cd6-a0daa61c444d.png)

Correct display
![image](https://cloud.githubusercontent.com/assets/12648552/13518657/9232074c-e18d-11e5-8c8b-a3a81b1ed2af.png)

**Comment by dro248** [comment]
Marked invalid because we did not implement Domestic Trade. See implementation pdf included in zip file.
