### ISSUE TITLE
 Chat Messages Window Display

### ISSUE THREAD

**Issue by parsonsjo1** [thyer/CS340winter2016#431]
When sending a message from any player the chat message window displays the victory points and map inside. Maybe it is just an extra feature that was implemented to make the chat look cool.

![image](https://cloud.githubusercontent.com/assets/12648552/13518714/0b91011a-e18e-11e5-992d-8f34b076ee8c.png)

**Comment by verdude** [comment]
WAD.

**Comment by matthewfcarlson** [comment]
We aren't sure why this does this but it's done it ever since we downloaded our client
