### ISSUE TITLE
Rolling a seven stops the game because of move the robber

### ISSUE THREAD

**Issue by parsonsjo1** [thyer/CS340winter2016#435]
I was rolling the dice and rolled a seven. This brought up move the robber for all four players.

![image](https://cloud.githubusercontent.com/assets/12648552/13519471/711d59be-e195-11e5-88be-37d840f443d0.png)

I tried to move the robber for one player and it worked, so I tested to see if it would work for another player and it did.

![image](https://cloud.githubusercontent.com/assets/12648552/13519495/89f6f9c2-e195-11e5-911b-841115b1db5f.png)

I then selected who to rob from, while I left the other two players alone (Move the robber display still up for them)

![image](https://cloud.githubusercontent.com/assets/12648552/13519510/9ae1ca46-e195-11e5-974b-7e1845111554.png)

I finished the turn of the player who rolled the seven and this activated the roll dice for the next player (top right) who still had the move the robber display. I thought that this would get rid of the display and allow the game to continue, but after clicking okay on the roll results the move the robber display popped back up and covered the finish turn bar, stopping the game from continuing.

![image](https://cloud.githubusercontent.com/assets/12648552/13519523/ad9466c6-e195-11e5-94b4-ca3e873e21d6.png)

![image](https://cloud.githubusercontent.com/assets/12648552/13519530/bef694b6-e195-11e5-8b55-a61ac7d4599b.png)

**Comment by kamenomagic** [comment]
I just simply forgot to check if it was the currentplayer's turn. This should resolve all of the related issues you posted, since it will only pop up for one player.
