### ISSUE TITLE
Team 4: domestic trade and maritime trade are still usable after game ends

### ISSUE THREAD

**Issue by matthewfcarlson** [thyer/CS340winter2016#437]
The you won modal pops up but once you close it you can still domestic trade and maritime trade.

**Comment by thyer** [comment]
@matthewfcarlson Are you logging a bug against your own team?

**Comment by matthewfcarlson** [comment]
Why no. Totally not. Please delete this.

**Comment by eaglewyng** [comment]
Wrong bug tracker.
