### ISSUE TITLE
Place Robber view shows two robbers

### ISSUE THREAD

**Issue by mountain01** [thyer/CS340winter2016#440]
Expected Results:
When Playing the robber I should only see one robber, which I can move and place, on the screen.

Actual Results:
There is a robber that follows the mouse, like it's supposed to, as well as a robber on the map at it's old position.

**Comment by misterpink14** [comment]
The client they give us also shows two Robbers, so it would seem this is working as expected. The user needs to be able to see where the Robber currently is so she/he knows the Robber cannot be placed there.

**Comment by mountain01** [comment]
Sounds good to me. You can close this one then. 

Get Outlook




On Thu, Mar 24, 2016 at 10:26 PM -0700, "misterpink14" <notifications@github.com> wrote:












The client they give us also shows two Robbers, so it would seem this is working as expected. The user needs to be able to see where the Robber currently is so she/he knows the Robber cannot be placed there.
