### ISSUE TITLE
Placing Robber on tile that you are next to doesn't work correctly

### ISSUE THREAD

**Issue by mountain01** [thyer/CS340winter2016#446]
Steps to duplicate:
Roll a 7. Place robber on tile you and another player are next to.

Expected Result:
I should be able to choose to rob from the other player.

Actual Result:
The rob player modal doesn't appear. Nothing happens.

<img width="1463" alt="screen shot 2016-03-24 at 8 05 51 pm" src="https://cloud.githubusercontent.com/assets/7536427/14036260/fdd591e2-f1fc-11e5-968e-d5c00a2b0180.png">

**Comment by misterpink14** [comment]
Did the other player have resources? Did you get a resource? Our modal only pops up if there is more than one player to rob. Otherwise it auto robs.
