### ISSUE TITLE
The Log Behaves when AI Rolls a 7

### ISSUE THREAD

**Issue by misterpink14** [thyer/CS340winter2016#462]
When you Roll a seven, the log behaves normally.
<img width="346" alt="screen shot 2016-03-24 at 10 41 11 pm" src="https://cloud.githubusercontent.com/assets/9299960/14038114/d92a8464-f211-11e5-950b-d4ef575fe91c.png">

When an AI Rolls a seven, the log spits out the same message about 20 times
<img width="346" alt="screen shot 2016-03-24 at 10 41 30 pm" src="https://cloud.githubusercontent.com/assets/9299960/14038122/f561c6b0-f211-11e5-96e6-3e96baec3a07.png">

To replicate this:
Create a game with you against 3 AI players. Play until the AI rolls a 7. View the log.

**Comment by jtmingus** [comment]
Same as the others about the AI (not implemented yet).
