### ISSUE TITLE
AI can place the robber on a water hex

### ISSUE THREAD

**Issue by misterpink14** [thyer/CS340winter2016#463]
This may be related to #462. An AI player can place the Robber on a water hex.
<img width="744" alt="screen shot 2016-03-24 at 10 46 52 pm" src="https://cloud.githubusercontent.com/assets/9299960/14038157/804b8e1e-f212-11e5-944c-f3d14a2ed5c8.png">

To recreate this:
Create a game against 3 AI's. Play until the AI rolls a seven and places the Robber on a water Hex.

**Comment by misterpink14** [comment]
The first time this happened, I rolled a 7 and was able to move the Robber. This time, I did not roll a 7 and the game froze. 
<img width="1348" alt="screen shot 2016-03-24 at 10 51 20 pm" src="https://cloud.githubusercontent.com/assets/9299960/14038205/17535fee-f213-11e5-864e-70bf96b27845.png">

**Comment by misterpink14** [comment]
It seems like the server is just in a bad state. I can't login or register either. The client freezes when I try.
<img width="340" alt="screen shot 2016-03-24 at 10 53 49 pm" src="https://cloud.githubusercontent.com/assets/9299960/14038235/725648f2-f213-11e5-9f21-cfecbf97af05.png">
<img width="320" alt="screen shot 2016-03-24 at 10 53 55 pm" src="https://cloud.githubusercontent.com/assets/9299960/14038236/76fd26dc-f213-11e5-8c27-612dd1c35f86.png">

**Comment by misterpink14** [comment]
It seems as though the Robber is always placed at this specific water hex when the AI rolls a 7.
<img width="699" alt="screen shot 2016-03-24 at 11 11 14 pm" src="https://cloud.githubusercontent.com/assets/9299960/14038407/cdb86ba6-f215-11e5-9b07-a7547b5a4634.png">

**Comment by jtmingus** [comment]
Like I said in the other issue, we didn't implement the AI (which was mentioned in the email we sent with the jars).
