### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by misterpink14** [thyer/CS340winter2016#464]
I can register as Kevin, which seems to be an existing player (first image). Also I can't join Kevin's game, which is probably the behavior it should be.
<img width="1068" alt="screen shot 2016-03-24 at 11 03 08 pm" src="https://cloud.githubusercontent.com/assets/9299960/14038335/de8c80a8-f214-11e5-98c2-3130fc72be24.png">

<img width="655" alt="screen shot 2016-03-24 at 11 03 23 pm" src="https://cloud.githubusercontent.com/assets/9299960/14038338/e2a555b6-f214-11e5-8bce-de3a549c9e88.png">

To recreate:
Register as Kevin. You can see that "Kevin" is in the saved game.

**Comment by jtmingus** [comment]
It was also mentioned in the email we sent with the jars that the default game won't work, which is why we named it "Invalid game."
