### ISSUE TITLE
The Game is consistently freezing after a few rounds

### ISSUE THREAD

**Issue by misterpink14** [thyer/CS340winter2016#465]
After a few rounds, the game freezes up.
<img width="1350" alt="screen shot 2016-03-24 at 11 15 37 pm" src="https://cloud.githubusercontent.com/assets/9299960/14038447/71e8cd06-f216-11e5-8733-bca18e49ab57.png">

As you can see, it shows that the AI's turn has ended. I have not been prompted with the roll dice popup and cannot end my turn. All other buttons do not work either, including the x at the top left. 

To recreate:
Create a game against 3 AI's. Play until the game freezes.

**Comment by jtmingus** [comment]
The AI isn't implemented fully. We just had it partially implemented (working ahead for phase 4). We mentioned in the email that we sent with the jar files to not play with AIs.

**Comment by misterpink14** [comment]
I'm so sorry! I definitely wasn't told that until a couple hours ago.

**Comment by jtmingus** [comment]
No problem!
