### ISSUE TITLE
Game freezes when trying to join a game

### ISSUE THREAD

**Issue by menyx02** [thyer/CS340winter2016#481]
Recreate: Register user 1 with any username and password
*Create a new game - go to the color picker but don't actually join the game, just select color
*Kill the client
*Start a new client and register with another player
*Create a new game but don't enter the game
*Kill the client
*Start up client 1 and sign in with the 1st player
*Enter the game the 1st player started, and sit at the color picker
*Start up client 2, and sign with 2nd player
*Join the game that 1st player created and sit at the color picker
*Go to client 1 and click join game
*The client completely freezes.

**Comment by el3ment** [comment]
either we fixed this with another fix (perhaps register) or it wasn't reproducible - per the TA's instructions, I am marking it invalid
