### ISSUE TITLE
Players can trade like resources in maritime trade

### ISSUE THREAD

**Issue by DallonTG** [thyer/CS340winter2016#486]
**Description**
According to the Catan rules, a player should not be able to trade like resources in either domestic or maritime trades. For example, a player should not be able to trade 3 sheep for 1 sheep in Maritime trade. I was able to do this. This may be a client bug and not a server one; I'm not sure.

![liketrades](https://cloud.githubusercontent.com/assets/16548246/14050862/5e36a512-f284-11e5-8a31-403b7e6723fb.PNG)

**Steps to reproduce**
1. Get enough resources to do a maritime trade
2. See that you can trade like resources.

2.

**Comment by hunterrees** [comment]
We specifically discussed this in class, though it is a dumb trade to make it doesn't have to be prevented.

**Comment by DallonTG** [comment]
I don't remember every little thing that is discussed in class. I just know that the official rules say you can't do it.
