### ISSUE TITLE
Swagger does not appear to be working

### ISSUE THREAD

**Issue by tcashcroft** [thyer/CS340winter2016#491]
We have not been able to get swagger to load - it is throwing 404 errors. It didn't look like the swagger pages were included in the jar...

**Comment by hunterrees** [comment]
Swagger works, but we weren't supposed to test with it, so it wasn't included in the zip

**Comment by tcashcroft** [comment]
I disagree -- We were supposed to be able to run commands with swagger, but we weren't supposed to be rude in our use of it. But it's how I would test joining a game without a valid cookie, or things of that nature (since the client locks us in)
