### ISSUE TITLE
Robber doesn't show when I start set-up

### ISSUE THREAD

**Issue by hunterrees** [thyer/CS340winter2016#493]
When I first begin set-up the robber isn't visible (after playing the first road the robber then appears)

**Comment by hunterrees** [comment]
![img_0558](https://cloud.githubusercontent.com/assets/16613772/14051709/a8750924-f28a-11e5-8306-cc9fc8bd64b2.jpg)

**Comment by mcrowder65** [comment]
Marked invalid cause this is client side and was the same bug reported for phase 2 but it was thrown out - confirming with bentz later.
