### ISSUE TITLE
Disappearing Settlement

### ISSUE THREAD

**Issue by tiubrian** [thyer/CS340winter2016#494]
sorry i don't know how to reproduce this but MrBurns only has 1 settlement and 1 victory point.

Here's a picture so you can see the game history on the left. I hope that helps

![apicture1](https://cloud.githubusercontent.com/assets/16830664/14051226/e4f7a3ba-f286-11e5-9994-96b20904fc83.png)

**Comment by tiubrian** [comment]
The original settlement was at the very top by the single road not on the wheat port

**Comment by mcrowder65** [comment]
marked invalid cuz it deals with AI's and it's only extra credit - @seattleite7 you can work on it if you want  i guess
