### ISSUE TITLE
Game hub page doesn't refresh

### ISSUE THREAD

**Issue by hydn** [thyer/CS340winter2016#498]
**Description**
When one client joins a game, the game hub does not update that change to the other clients.

**Steps to reproduce**
1. Open several clients
2. Have one client join a game
3. Check the other clients

**Screenshots**
![image](https://cloud.githubusercontent.com/assets/1923965/14051128/2edffe38-f286-11e5-98ce-1fd97bf329ba.png)
(This screenshot was taken after two more players had joined the bottom game.)

**Comment by hunterrees** [comment]
In Phase 2 this was listed as a bug, but after talking with Bentz we were told it wasn't necessary.
