### ISSUE TITLE
Can't Create New Game with all 3 checked

### ISSUE THREAD

**Issue by ztnelson01** [thyer/CS340winter2016#501]
Randomly placed numbers, Randomly placed Hexes, and Randomly placed ports all checked. Game not showing up after hitting create.
![gamewitheverything](https://cloud.githubusercontent.com/assets/16672513/14051509/1904be5c-f289-11e5-86c1-641a5c7920a2.png)
![gamewitheverythingdidn tappear](https://cloud.githubusercontent.com/assets/16672513/14051510/1a24fa54-f289-11e5-84f0-14a95d9977d2.png)

**Comment by mcrowder65** [comment]
Marked invalid cause we've made over 1000 games and this has never happened to us - if we ever reproduce it we'll mark valid and fix it.
