### ISSUE TITLE
Team 13 - Create game - random hexes

### ISSUE THREAD

**Issue by tiubrian** [thyer/CS340winter2016#502]
When I create a game with only randomly placed hexes. And each time the desert is always at the top.

Also I asked the ta's about this when the hexes are randomly placed, the numbers are supposed to move  with it and not stay in the same place on the map.  This will also fix the problem that the desert hex never gets randomly moved.

**Comment by mcrowder65** [comment]
I'm confused, are the numbers supposed to stay with the hexes? @tiubrian, thanks in advance!

**Comment by tiubrian** [comment]
Sorry I'm just seeing this I had a busy weekend.
so each hex has a number assigned to it. so when the hexes move to different spots, the number assigned to that hex is the same. 
example:
if hex at position -1,2 is assigned the number 5, if  that hex type is moved randomly to position 0,0, that hex number should still be number 5. and since the number stays with the hex type, then the desert can be randomly placed too without the numbers being randomly assigned

**Comment by mcrowder65** [comment]
Great, I think I fixed it. Thanks!

**Comment by tiubrian** [comment]
oh i just realized you already have the fixed label lol
