### ISSUE TITLE
Team 13 - Monument

### ISSUE THREAD

**Issue by tiubrian** [thyer/CS340winter2016#503]
You should be able to play monument cards anytime including when you buy it on that turn. But you can't play any until it lets you win

**Comment by mcrowder65** [comment]
@bbarney7 How do we handle this? I thought we encountered this and specifically fixed it?

**Comment by mcrowder65** [comment]
However, this is client side... @bbarney7

**Comment by bbarney7** [comment]
<img width="409" alt="screen shot 2016-03-26 at 2 00 34 pm" src="https://cloud.githubusercontent.com/assets/14189637/14062177/2f6a3834-f35b-11e5-8110-35240833a576.png">

Invalid because we follow the official rules of catan
