### ISSUE TITLE
Team 13 - map not showing

### ISSUE THREAD

**Issue by tiubrian** [thyer/CS340winter2016#505]
I registered 4 different users.
i made them all join a game one at a time. after the last player joins, this is what I get.  
Only the last person that joins has a visible map. the rest don't
![nomap6](https://cloud.githubusercontent.com/assets/16830664/14051852/79de3cb0-f28b-11e5-9e7f-91b03e99203a.png)

**Comment by tiubrian** [comment]
It just happened to me again. but sometimes it works. so it might be a little hard to reproduce

**Comment by mcrowder65** [comment]
Could you elaborate more? I'm not trying to tell you you're lying, but it's weird that the other three have red banners and red isn't even a color on the one where the map drew? We've never had this happen @tiubrian @hunterrees

**Comment by mcrowder65** [comment]
Marking invalid until we get better reproduction tips
