### ISSUE TITLE
When all players are joined, 1st player needs to re-join game in order to continue

### ISSUE THREAD

**Issue by CaptBoscho** [thyer/CS340winter2016#513]
Once all 4 players are added to the game and the game is starting, the create game/join game module is still up on the first player's client. Need to re-join game in order to start.

**Comment by eaglewyng** [comment]
Do you mean that the first player is returned to the game selection screen after creating a game?

**Comment by matthewfcarlson** [comment]
I haven't been able to reproduce this but we will keep testing. Any more details? Though from what it sounds the first player was at the game info modal and you do need to click re-join in order to be a part of the game.

**Comment by CaptBoscho** [comment]
Well I already joined but then when all 4 players are in,  or perhaps it's because the Gabe stays,  but either way 1st player is kicked out and must rejoin the game

**Comment by matthewfcarlson** [comment]
I've joined a game with four human players before (all four clients running at the same time) many times and I've never seen this. There's another bug that the fourth client when joining errors out and needs to be restarted. We are going to need more details to be able to reproduce this.

**Comment by matthewfcarlson** [comment]
Based on what you've said we think this is actually a feature. When you create a game, you need to be joined to it. However, by design it takes you to the game list modal. The spec is ambiguous on what happens when you need to join but it seems to see that this is the intended behavior. I think this bug is invalid. @eaglewyng

**Comment by thyer** [comment]
@CaptBoscho was the first user's client actually looking at the PlayerWaiting screen when he/she was kicked out and brought back to the login screen?
