### ISSUE TITLE
Can't see wheat icon

### ISSUE THREAD

**Issue by CaptBoscho** [thyer/CS340winter2016#519]
![screenshot from 2016-03-25 14-37-32](https://cloud.githubusercontent.com/assets/16085533/14053494/3e48196c-f297-11e5-9583-257992733a65.png)

**Comment by CaptBoscho** [comment]
I realize it's a petty error but just logging what I see haha

**Comment by matthewfcarlson** [comment]
Evidence suggests that this is a GUI code bug specific to linux.

**Comment by matthewfcarlson** [comment]
We have just confirmed that the wheat icon pops up on windows and mac.

**Comment by thyer** [comment]
View thing, that's the TAs' fault
