### ISSUE TITLE
Turntracker getting stuck at AI turn when you exit and rejoin

### ISSUE THREAD

**Issue by mcrowder65** [thyer/CS340winter2016#522]
I created a game with 3 ai’s, started the setup rounds, and quit and rejoined the game a couple times and then it got stuck on the ai’s turn. https://drive.google.com/file/d/0BxYl7lEbWcxrbWxxbHg4TkxMTUU/view?usp=sharing

**Comment by danielmhair** [comment]
We did not implement AI's. This should be invalid

**Comment by mcrowder65** [comment]
Closing because AIs are extra credit
