### ISSUE TITLE
When robbing, says player has 0 cards when they have more

### ISSUE THREAD

**Issue by CaptBoscho** [thyer/CS340winter2016#526]
When robbing after a discard phase (don't know about other robbing situations) says player has 0 cards when they have a lot of cards.

![screenshot from 2016-03-25 14-49-34](https://cloud.githubusercontent.com/assets/16085533/14053709/db067108-f298-11e5-903b-24b6681f8899.png)

**Comment by eaglewyng** [comment]
I have noticed this as an intermittent issue. Marking as valid, thanks!

**Comment by eaglewyng** [comment]
Fixed by both @matthewfcarlson and @eaglewyng

**Comment by matthewfcarlson** [comment]
Hahaha my bad.

**Comment by thyer** [comment]
Dupe
