### ISSUE TITLE
Maritime Trade isn't enabled when I should be able to 3:1 trade

### ISSUE THREAD

**Issue by CaptBoscho** [thyer/CS340winter2016#529]
Connected to the 3:1 port but I can't Maritime trade

![screenshot from 2016-03-25 14-56-51](https://cloud.githubusercontent.com/assets/16085533/14053848/e4f426fa-f299-11e5-8ed9-ee1195648c71.png)

**Comment by matthewfcarlson** [comment]
I'll work on this @eaglewyng

**Comment by matthewfcarlson** [comment]
@CaptBoscho I am going to need more details. So the maritime trade button should be enabled whenever it's your turn. The fact that it's not is concerning. I think this might be a incorrect state condition. It looks like you rolled a 7 and took an ore so it could be in an inconsistent state afterwards.

**Comment by eaglewyng** [comment]
@matthewfcarlson I know if you domestic trade once, it disables both buttons, so this may perhaps be the same bug as #648.

**Comment by CaptBoscho** [comment]
Either of those could be true

**Comment by matthewfcarlson** [comment]
@eaglewyng Based on what has been reported, I think this is the same bug, so it should be marked as duplicate. 

@CaptBoscho, if you have any other details that would suggest it to be different than #648 or #527 please let us know.
