### ISSUE TITLE
Multiple Players with the same color

### ISSUE THREAD

**Issue by joshuahaertel** [thyer/CS340winter2016#534]
I log in as Sam, open up the first game, choose my color as Red and I have the same color as Pete. Hard to decide severity level. It's simple style error, P5, but it also leads to confusing gameplay, P3. Feel free to discuss the severity with Bentz, but for now I'll put it in between at P4.

![screen shot 2016-03-25 at 4 06 50 pm](https://cloud.githubusercontent.com/assets/16691565/14054996/9e2db6c8-f2a3-11e5-91af-96665815d6bf.png)

**Comment by joshuahaertel** [comment]
I'm keeping this one open for now because I think the Server should probably check for valid color input.

**Comment by joshuahaertel** [comment]
Similarly, I open four clients up, I run log Mark into the first with Green and then I log Pete into the next. He is unable to select Red as a color. This is very likely a server error where the colors are not being outputted properly.

**Comment by joshuahaertel** [comment]
For him and Brooke, white is off limits although no player has that color. Once Pete and Mark go to login they are able to select the full array of valid colors. Again, that part is likely a Phase 2 error, it is hard to tell, but the server should not allow the color duplication in the first part.

**Comment by zlohner** [comment]
Which client are you using?

**Comment by joshuahaertel** [comment]
This is on your client. Here is a screenshot of when I log in as Sam on a clean server.

![screen shot 2016-03-26 at 12 37 02 pm](https://cloud.githubusercontent.com/assets/16691565/14061791/914b75c4-f34f-11e5-8aec-1cdf20e8a8fc.png)

It does appear to match the swagger output though:

  {
    "id": 0,
    "players": [
      {
        "name": "Sam",
        "id": 0,
        "color": "red"
      },
      {
        "name": "Brooke",
        "id": 1,
        "color": "blue"
      },
      {
        "name": "Pete",
        "id": 10,
        "color": "white"
      },
      {
        "name": "Mark",
        "id": 11,
        "color": "green"
      }
    ],
    "title": "default"
  },

But when I choose red as my color, this happens:

![screen shot 2016-03-26 at 12 38 39 pm](https://cloud.githubusercontent.com/assets/16691565/14061796/b1298660-f34f-11e5-9de1-0f599710b128.png)

Which verifies that this is indeed a server error.

Thinking about our design, I can offer my ideas as to where the error might actually be. For now though, it is probably enough to say that what games/list says the game looks like is not what game/model says what the game looks like.

**Comment by zlohner** [comment]
Found the problem - this only happened in the default game, and it resulted from an inconsistency between the players we initialized and the default game loaded from the JSON file. Fixed.
