### ISSUE TITLE
Longest Road (Phase 3, Team 6)

### ISSUE THREAD

**Issue by matthewfcarlson** [thyer/CS340winter2016#544]
Longest road kicks in 1 road and for the wrong player (see my previous bug about the road builder). 
<img width="1375" alt="screen shot 2016-03-25 at 4 24 00 pm" src="https://cloud.githubusercontent.com/assets/6557490/14055341/ce8ccc16-f2a6-11e5-986a-c64202287d3e.png">

**Comment by matthewfcarlson** [comment]
However, for the wrong player is because of the previous bug.

**Comment by thyer** [comment]
Closing this as dupe of previous bug
