### ISSUE TITLE
D-Trade gives to the "accepter" what the accepter was to give away.

### ISSUE THREAD

**Issue by CaptBoscho** [thyer/CS340winter2016#55]
Say i'm trading player Bob 1 wheat for 1 brick, Bob gains a brick instead of a wheat and he doesn't lose his brick.

**Comment by DanielSaunders** [comment]
Fixed with commit d1daba39c71d2646e3b6e64f4698de5111bad51b. 
Just needed to swap some variables.

**Comment by CaptBoscho** [comment]
Remember to label any things you fixed as "fixed" :)

**Comment by CaptBoscho** [comment]
not necessarily closed
