### ISSUE TITLE
Games List not showing new games

### ISSUE THREAD

**Issue by jtmingus** [thyer/CS340winter2016#550]
When you have multiple players logged in, if one player creates a game, it doesn't show up for the other clients.  You have to restart the client to see it.

![screenshot from 2016-03-25 16 35 01](https://cloud.githubusercontent.com/assets/11638796/14055437/ab89cf88-f2a7-11e5-9450-477a1abe5e3e.png)

**Comment by yeyyosing** [comment]
Where is this in the specification? We didnt think that you needed a poller on this controller so we didnt put one.

**Comment by yeyyosing** [comment]
Please attach a screenshot of where this is in the spec

**Comment by jtmingus** [comment]
I guess we just interpreted it from the first line in the functional spec about the game hub. We considered any newly created game a "current available game". But also when a player joins the game, the other clients don't update to show those new players in the list.  
![image](https://cloud.githubusercontent.com/assets/11638796/14058349/fa5c49b6-f2e2-11e5-9ecf-9e84afaa3188.png)

You might be right though, cause I see how this could be interpreted differently!

**Comment by thyer** [comment]
No forced updates, as long as games are displayed at time of login and no incorrect behavior is allowed, this is functional
