### ISSUE TITLE
Not able to rob player

### ISSUE THREAD

**Issue by kking937** [thyer/CS340winter2016#555]
I placed the robber on a hex with 2 buildings on it: 1 mine, 1 another players.  No modal popped up to rob a player.

**Comment by yeyyosing** [comment]
this isn't a bug.  it automatically robs that one player.  this makes sense since there is only one player to rob from

**Comment by thyer** [comment]
Agreeing with @yeyyosing since we worked this out together last phase. I like his solution better than giving somebody only one option since it provides fewer avenues for bug introduction.
