### ISSUE TITLE
Rolling modal pops up again when 7 is rolled

### ISSUE THREAD

**Issue by wesleyackerman** [thyer/CS340winter2016#560]
When a 7 is rolled, and the robbing occurs, the dice roll modal usually pops up again. Pressing "Roll" doesn't do anything, but I have to do it to make the modal go away.

**Comment by misterpink14** [comment]
I'm not able to replicate this. For me, the modal doesn't pop up, it's just still there (which is a bug), but there is no roll button (the 7 is just still displayed). Could you possibly send a screenshot; or better yet, replication steps? Thanks!

**Comment by misterpink14** [comment]
@wesleyackerman ^^
