### ISSUE TITLE
Resources Do Not Decrement

### ISSUE THREAD

**Issue by joshuahaertel** [thyer/CS340winter2016#561]
I place a city and my resources and cities remain the same. Cities only change after I end my turn.

Pre-City
![screen shot 2016-03-25 at 4 48 28 pm](https://cloud.githubusercontent.com/assets/16691565/14055739/eb0fd0ba-f2a9-11e5-881d-3bd1a164d1a1.png)

Post-City
![screen shot 2016-03-25 at 4 48 51 pm](https://cloud.githubusercontent.com/assets/16691565/14055741/f02d1a44-f2a9-11e5-8289-e28878b63b31.png)

Post-Finish Turn
![screen shot 2016-03-25 at 4 52 24 pm](https://cloud.githubusercontent.com/assets/16691565/14055746/fed9df64-f2a9-11e5-88e6-83c1df7f01f3.png)

**Comment by zlohner** [comment]
Which client are you using?

**Comment by joshuahaertel** [comment]
As this was the case with the past few errors, I believe this and all other errors reported were with your client.

**Comment by zlohner** [comment]
we haven't been able to reproduce this bug - building a city correctly decreases resources (2x wheat and 3x ore), decrements available cities, increments settlements, adds a victory point, and places the city on the map immediately, with no need to wait until the turn is finished. Could you give us some more detail about how this particular game was set up so we can try to find the problem?

**Comment by joshuahaertel** [comment]
I opened a client for each user with their appropriate colors when it was their turn in the 1st game. I rolled a couple of times until there were some resources. I made some trades in order to get Pete into a position to place a city.
Before I place a city:
![screen shot 2016-03-28 at 1 10 27 pm](https://cloud.githubusercontent.com/assets/16691565/14087404/20ae7b88-f4e7-11e5-9188-db9fe664c73c.png)


After I place a city:
![screen shot 2016-03-28 at 1 10 45 pm](https://cloud.githubusercontent.com/assets/16691565/14087413/263a8be6-f4e7-11e5-8e56-5eeb9bd1cddb.png)


After I end my turn:
![screen shot 2016-03-28 at 1 11 01 pm](https://cloud.githubusercontent.com/assets/16691565/14087416/2a8f8106-f4e7-11e5-978d-027e22a56e1a.png)

**Comment by joshuahaertel** [comment]
Here is the JSON Swagger gave me for building a city with Mark right after that
[mark-pre-build.txt](https://github.com/thyer/CS340winter2016/files/192362/mark-pre-build.txt)
[mark-post-build.txt](https://github.com/thyer/CS340winter2016/files/192360/mark-post-build.txt)
[mark-post-turn.txt](https://github.com/thyer/CS340winter2016/files/192361/mark-post-turn.txt)

His resources remain constant the whole time. His cities decrease properly, though it is not reflected in the client until he finishes his turn.

**Comment by joshuahaertel** [comment]
In both cases I made trades before-hand in order get the appropriate amount of resources.

**Comment by joshuahaertel** [comment]
I'll try to thin this out, but I just noticed the server spitting this out:

[server-exception.txt](https://github.com/thyer/CS340winter2016/files/192381/server-exception.txt)

**Comment by joshuahaertel** [comment]
Again, I start game 1, everyone rolls once, I made a trade so that the given player (Sam in this case) could build a city. Here is the server output:
[server-exception-city.txt](https://github.com/thyer/CS340winter2016/files/192393/server-exception-city.txt)

I did not appear to get any more output when I finished my turn.
