### ISSUE TITLE
No Points for Cities

### ISSUE THREAD

**Issue by joshuahaertel** [thyer/CS340winter2016#564]
I bought two cities but do not increase in victory points.

![screen shot 2016-03-25 at 4 52 24 pm](https://cloud.githubusercontent.com/assets/16691565/14055807/7558d852-f2aa-11e5-8a4c-030012b4ccdd.png)

**Comment by zlohner** [comment]
Which client are you using?

**Comment by zlohner** [comment]
#561

**Comment by zlohner** [comment]
#561
