### ISSUE TITLE
Monument cards

### ISSUE THREAD

**Issue by jjwilbur** [thyer/CS340winter2016#568]
You should be able to play monument cards as soon as you have them.  You guys have them disabled unless when you play it, it will allow you to finish the game. 

For example, If I have 8 points and I have 2 monument cards in my dev hand then you can play them to finish the game.  If You only had 5 points and had 2 monument cards it doesn't allow you to play them. I believe you should be able to play monument cards as soon as you draw them.  The only dev card that as soon as you draw it you can play it. All other dev cards you can't play the card until your next turn.

**Comment by yeyyosing** [comment]
This isn't a bug.  We built the game to operate the way a game in real life would work.  We purposely made it so that you can only play monument cards if it allows you to win.
