### ISSUE TITLE
Bank Ran Out Of Resources Too Fast - Unplayable game

### ISSUE THREAD

**Issue by joshuahaertel** [thyer/CS340winter2016#585]
This error could be under the umbrella of some of the previous ones, but for some reason at about the halfway point of a the game, the bank ran out of resources. I will try to to checkout the JSON from swagger to see if I can offer more helpful feedback, but I do not believe this should be happening so quickly.

**Comment by joshuahaertel** [comment]
Specifically, it could be related to bug 561

**Comment by joshuahaertel** [comment]
I just ran through the game just placing roads and cities and buying and playing dev cards - which on the surface have proper functionality - and the bank ran out of resources in the middle again. Due to time, I cannot pinpoint where the error might be, but perhaps one of those previously mentioned operations takes resources away from the bank as well as the player.

**Comment by zlohner** [comment]
We had forgotten to add the resources back to the bank after buying things, this is now fixed.
