### ISSUE TITLE
Rolling a 7 sometimes freezes the game

### ISSUE THREAD

**Issue by byurfl** [thyer/CS340winter2016#590]
I haven't seen a pattern to this yet, but it has happened to me twice now. Only the client who rolled the 7 is affected. Restarting the client fixes the issue.

![image](https://cloud.githubusercontent.com/assets/17560567/14056374/a710e532-f2b0-11e5-8ba2-e54c7d83920e.png)

**Comment by yeyyosing** [comment]
please stop with the freezing bugs.  if it freezes then log it once.  thank you

**Comment by byurfl** [comment]
You're right, this belongs with #558. Sorry about that.
