### ISSUE TITLE
Cannot create multiple games with same name

### ISSUE THREAD

**Issue by hydn** [thyer/CS340winter2016#593]
**Description**
I cannot create a game that has the same name as another game. The specification does not indicate that game titles need to be unique.

**Steps to reproduce**
1. Create game
2. Attempt to create another game with the same name

**Screenshots**
![image](https://cloud.githubusercontent.com/assets/1923965/14056659/7c0bb62e-f2b4-11e5-86c6-f0c3daa9eff4.png)

![image](https://cloud.githubusercontent.com/assets/1923965/14056664/878f7e68-f2b4-11e5-8637-3cde4f99777e.png)

![image](https://cloud.githubusercontent.com/assets/1923965/14056670/91392662-f2b4-11e5-8f15-a2879d1dc870.png)

**Comment by hunterrees** [comment]
The opposite of this was logged as a bug in Phase 2, so this is invalid.
