### ISSUE TITLE
Create nameless game

### ISSUE THREAD

**Issue by misterpink14** [thyer/CS340winter2016#598]
You can create a game that does not have a title

<img width="399" alt="screen shot 2016-03-25 at 7 05 43 pm" src="https://cloud.githubusercontent.com/assets/9299960/14057143/d3cc3192-f2bc-11e5-861a-c454f7169969.png">

<img width="1065" alt="screen shot 2016-03-25 at 7 05 52 pm" src="https://cloud.githubusercontent.com/assets/9299960/14057144/da03b742-f2bc-11e5-957d-9bd3cc658939.png">

**Comment by kking937** [comment]
Fixed, but no box pops up
