### ISSUE TITLE
Can open domestic trade when it's not your turn

### ISSUE THREAD

**Issue by DallonTG** [thyer/CS340winter2016#6]
**Description:**
You can open the domestic trade modal when it is not your turn. Then, when you cancel the trade, a null pointer exception occurs and you can never exit the modal until you restart the client.

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException at client.controllers.trade.domestic.DomesticTradeController.cancelTrade(DomesticTradeController.java:351)
at client.views.trade.domestic.DomesticTradeOverlay$2.actionPerformed(DomesticTradeOverlay.java:116)
        ...`

**Steps to reproduce:**
Open domestic trade when it's not your turn.

**Comment by thelaurence** [comment]
For some reason when I ran the code locally, this was a non-blocking error. I was able to close the modal and continue playing. For some reason this behavior did not carry over to the .jar we submitted for testing. Hopefully we can downgrade this to a P3 bug.
