### ISSUE TITLE
Can make 2 clients join at the same time

### ISSUE THREAD

**Issue by jakebrucebrewer** [thyer/CS340winter2016#601]
1. log in as Pete
2. create a new game with pete
3. open a 2nd client. 
4. log in a 2nd time as pete. 
5. Join the game that was crated by the 1st client. 
6. both clients enter the game interface at the same time.

**Comment by thyer** [comment]
I believe that this is actually allowed...it's similar to being able to email from your phone and desktop simultaneously. As long as the server doesn't allow bugs (like the double settlement placement you found), and keeps everything synchronized, it's fine.

**Comment by jakebrucebrewer** [comment]
Sounds good.
