### ISSUE TITLE
Can Apparently Create Games While Not Logged In

### ISSUE THREAD

**Issue by panzertime** [thyer/CS340winter2016#609]
I closed and restarted the server, thus losing the user I had created.  However, I did not refresh Swagger after I restarted the server, and was still "logged in" as that user.  I used Swagger to create a new game while "logged in" as a user before having actually created that user.

**Comment by panzertime** [comment]
I was able to join the game and do several other things in a state like this.  It appears that as long as the client/browser has a properly-formatted cookie, he can make the server do anything even if that cookie isn't for a valid user.

**Comment by bbarney7** [comment]
You are not supposed to be doing heavy testing through swagger- check the specs

**Comment by zlohner** [comment]
If the server shuts down and restarts a client is still supposed to be able to store a cookie and be logged in. We will add authentication on commands to make sure the cookie is still for a valid user.
