### ISSUE TITLE
Cannot (Add Normal Players In Order To) Join Created Game

### ISSUE THREAD

**Issue by panzertime** [thyer/CS340winter2016#615]
I created a user Carl and a game, and joined the game as Carl (in Swagger).  Then I created Bob, logged in as Bob, and tried to join Carl's game.  I couldn't, and when I called /games/list, I saw that this game had Carl, and had just Bob's color but not his ID or name.

**Comment by panzertime** [comment]
This is also broken with clients.

**Comment by zlohner** [comment]
Which client are you using? Please use our client to test this, not your own or the demo client.

**Comment by zlohner** [comment]
We have not been able to reproduce this bug either through Swagger or on our client, following the same steps as described. Were all inputs through Swagger valid? What had happened on this server previous to this test? Is there anything else you can think of that you did that we might not have done that we could try to reproduce this?

**Comment by panzertime** [comment]
All of the inputs on Swagger were valid.  The whole procedure here was done in Swagger.  I reset the server and did this a second time from scratch just to confirm that this isn't an artifact of something else and had the same thing happen.
