### ISSUE TITLE
Player can effectively build infinite roads in setup phase

### ISSUE THREAD

**Issue by DanielSaunders** [thyer/CS340winter2016#630]
The player can place as many free roads in the setup phase as desired when only one road should be permitted. If a user logs into multiple clients during the setup phase (specifically before that player has placed a road piece) they can go through every client and build another road piece, as long they don't place a settlement on any of the clients.

The following scenario was created using 2 clients for the blue player and 4 clients for the brown player.
![screenshot from 2016-03-25 21-47-11](https://cloud.githubusercontent.com/assets/13978907/14057896/87792284-f2d3-11e5-9629-f78834657762.png)

**Comment by misterpink14** [comment]
Hmm...this doesn't seem to be an issue with our server/client. Are you sure you were running ours?
