### ISSUE TITLE
Domestic Trade has graphical error that prevents intelligibility

### ISSUE THREAD

**Issue by DanielSaunders** [thyer/CS340winter2016#637]
As seen in the following example of a domestic trade, it is impossible to tell what the offering player is offering in their trade. (It was 1 ore resource)
![screenshot from 2016-03-25 22-02-17](https://cloud.githubusercontent.com/assets/13978907/14057953/9a6cfe7c-f2d5-11e5-8257-556426a5699b.png)

In the following example, the resource being offered is wheat.
![screenshot from 2016-03-25 22-03-34](https://cloud.githubusercontent.com/assets/13978907/14057960/b29b58c2-f2d5-11e5-8497-2bd428dff234.png)

**Comment by bopace** [comment]
I'm unable to replicate this bug. Are there any specific circumstances when this happens?

**Comment by DanielSaunders** [comment]
Hmm, that's weird. Just always seemed to happen to me. Any time I did a domestic trade, the icon for the resource on top didn't show up.

**Comment by bopace** [comment]
Strange. Did it work with multiple resources? The icon always appears for me, regardless of how many resources are traded.

**Comment by misterpink14** [comment]
@DanielSaunders Were you using linux by chance?

**Comment by DanielSaunders** [comment]
Yep. Is it just an issue on Linux?

**Comment by misterpink14** [comment]
That's what we are thinking, another group has confirmed it though
