### ISSUE TITLE
Maritime 4 of anything: 1 wheat => doesn't give me a wheat.

### ISSUE THREAD

**Issue by CaptBoscho** [thyer/CS340winter2016#64]

**Comment by DanielSaunders** [comment]
Cannot reproduce. I could trade 4 brick for 1 wheat. I could also trade 4 wheat for a wood. Does not seem to be a problem. Perhaps it has been fixed inadvertently?

**Comment by CaptBoscho** [comment]
I was trading 4 wood for 1 wheat and I wasn't getting the wheat back. I'll verify

**Comment by CaptBoscho** [comment]
You're right, I'm sorry haha
