### ISSUE TITLE
Doesn't stop the player from playing a monument card when they don't have enough points to win.

### ISSUE THREAD

**Issue by cmriboldi** [thyer/CS340winter2016#646]
There is nothing that stops the player from playing a monument card before they have enough monument cards to win the game. It's a rule that the player can only play monument cards when they have enough to win the game. Otherwise you can't play them.

**Comment by mountain01** [comment]
Demo also allowed this I'm pretty sure

**Comment by thyer** [comment]
Given that this is a bit of a religious war in the board game itself, I'm not going to enforce either preference.
