### ISSUE TITLE
Can create new game with same name as existing game. 

### ISSUE THREAD

**Issue by jakebrucebrewer** [thyer/CS340winter2016#649]
![screen shot 2016-03-25 at 10 44 03 pm](https://cloud.githubusercontent.com/assets/10167955/14058097/3acae208-f2db-11e5-8b7f-3c7ee66632d4.png)

**Comment by jvansteeter** [comment]
I don't think this is a true bug, there's no specification saying that the name of a game needs to be unique, and as long as each game has a unique ID it shouldn't be a problem.

**Comment by thyer** [comment]
Nothing in the specs against this
