### ISSUE TITLE
Doesn't let the player play a second development card the next turn.

### ISSUE THREAD

**Issue by cmriboldi** [thyer/CS340winter2016#653]
There is a null pointer exception that is stopping me from playing any additional development cards. This results in a lot of issues. I can't win by playing monument cards. I can't play soldier cards to win. I can't get resources from others to win. Basically it's very difficult to win :) especially since my strategy was development cards and they are all broken. I could log them as a bung of separate bugs but I'm pretty sure they come from the same error. Unfortunately, there are probably other bugs I can't test because this one prohibits me from even playing the cards.

**Comment by wesleyackerman** [comment]
What do you mean by "additional" development cards? The rules state you are only allowed to play one dev card per turn.

**Comment by thyer** [comment]
@cmriboldi could you clarify what causes the exception? Is it anytime the second DevCard is played, even if it's only attempted the next turn?

**Comment by thyer** [comment]
Closing for lack of additional information
