### ISSUE TITLE
Fifth player in game

### ISSUE THREAD

**Issue by bopace** [thyer/CS340winter2016#670]
A fifth player can join a game if they get to the color select modal before the other players have joined. They get in-game and can have Domestic Trade pop up, but nothing else works.
![bug2](https://cloud.githubusercontent.com/assets/15786690/14058319/fcc67cf4-f2e1-11e5-8979-7fb7d8dca366.png)

**Comment by kking937** [comment]
Can you give us the steps to reproduce?

**Comment by byurfl** [comment]
@kking937, I was able to reproduce this one. Open 5 clients, create a new game with one of them. Have all players join the game, but don't go beyond the color-selection screen. Then the last player to "finish" joining the game will be in the state @bopace described.
