### ISSUE TITLE
I close the game. Rejoin it again. The game freezes and everybody is stuck

### ISSUE THREAD

**Issue by jrwalther** [thyer/CS340winter2016#673]
It is my turn but I can't do anything

**Comment by jrwalther** [comment]
I am using your client

**Comment by zlohner** [comment]
Can you give us a bit more detail on how to reproduce this? This doesn't happen for us.

**Comment by zlohner** [comment]
We haven't been able to reproduce this at all in any game, can you please give us more specific conditions under which this occurs?

**Comment by zlohner** [comment]
#577 Next Player Cannot Go
