### ISSUE TITLE
Road build second round

### ISSUE THREAD

**Issue by verdude** [thyer/CS340winter2016#681]
Can't place road where It should be allowed to be placed. I think this is just a client issue.

Here is a screen shot:

![image](https://cloud.githubusercontent.com/assets/5685655/14058333/a1b9a92a-f2e2-11e5-825b-d5576c6d4185.png)

**Comment by seanag0234** [comment]
A road shouldn't be able to be placed there during the setup phase, because it would place a settlement too close to the other settlement.
