### ISSUE TITLE
Add AI Players dialog button causes problems 

### ISSUE THREAD

**Issue by eaglewyng** [thyer/CS340winter2016#71]
The add AI Players dialog crashes and brings us to the main game window when "Add a computer player" is clicked, which is then perpetually stuck in "Game Setup." If the AI functionality isn't implemented yet or the AI list is empty, it would be best to disable the "Add a computer player" button altogether instead of locking the user in the Game Setup phase.

**Comment by misterpink14** [comment]
In what case? I cannot seem to recreate this bug. Maybe I am looking at it incorrectly. Thanks!
