### ISSUE TITLE
Purchased Dev Card, got Monument, Able to instantly play card

### ISSUE THREAD

**Issue by matthewbahr** [thyer/CS340winter2016#72]
Purchased Dev Card, got Monument, Able to instantly play card
Points updated. Not supposed to be able to pay monument unless 10 points according to game rules but not listed anywhere on rubric
" You may only reveal them during your turn and when you are sure that you have 10 victory points—that is, to win the game. "

**Comment by hunterrees** [comment]
That is what is supposed to happen according to the functional spec
