### ISSUE TITLE
game history update did something strange

### ISSUE THREAD

**Issue by thelaurence** [thyer/CS340winter2016#73]
![image](https://cloud.githubusercontent.com/assets/10649804/13449284/0fc32234-dfe7-11e5-837a-4a09f94a8ea6.png)

**Comment by hunterrees** [comment]
@thelaurence  Can you give us any details of when/how it happened?

**Comment by thelaurence** [comment]
@hunterrees I played through another game with AI's trying to get this to happen again and I couldn't. I don't remember how I did it. Marking invalid and closing.
