### ISSUE TITLE
Frozen client, force close 

### ISSUE THREAD

**Issue by matthewbahr** [thyer/CS340winter2016#75]
Waited on timer to roll, hit close: entire view locked up and would not continue. I rolled a 9. I had 1 dev card.

**Comment by thyer** [comment]
@matthewbahr it seems as though you are reporting in this and your subsequent issue that (1) the issue causes indefinite corruption to the game even after quitting the client and reopening and (2) the issue can be duplicated anytime 1 dev card is held in the hand and a 9 is rolled. Are both of these items correct?

**Comment by matthewbahr** [comment]
This was subsequent to the previous locking and I was unable to take a turn after restarting the code.

After this breakdown I was able to play the game to completion. 

This issue forced me to use task manager to close while the other was only a locking the view.

**Comment by matthewbahr** [comment]
This was what happened before the next issue, it appeared to be a locked view. I was able to exit using normal methods.

**Comment by hunterrees** [comment]
@matthewbahr Do you have any other details on how to replicate?
