### ISSUE TITLE
Client Frozen

### ISSUE THREAD

**Issue by matthewbahr** [thyer/CS340winter2016#76]
Reopened after last close, played road building, bought a dev card, entire client froze.

Froze and crashed, cannot exit client, request worked - had new card and less resources after reopening

**Comment by matthewbahr** [comment]
This was subsequent to the previous locking and I was unable to take a turn after restarting the code.

After this breakdown I was able to play the game to completion. 

This issue forced me to use task manager to close while the other was only a locking the view.

**Comment by hunterrees** [comment]
@matthewbahr Did it freeze when you clicked to buy a dev card?
