### ISSUE TITLE
Discard modal appeared twice and client froze

### ISSUE THREAD

**Issue by thelaurence** [thyer/CS340winter2016#80]
Was in a game against computer players and one of the computers rolled a 7. This resulted in the discard modal being presented. After submitting the discard, the modal briefly closed and then reopened, but the reopened modal was non-responsive.

Sorry I don't have more detailed instructions of how to reproduce this.

**Comment by hunterrees** [comment]
@thelaurence How many cards did you have when the discard modal came up?

**Comment by thelaurence** [comment]
@hunterrees I should have taken a screenshot. I don't know how many resources I had.
