### ISSUE TITLE
After seemingly normal roll and OK, totally non-responsive

### ISSUE THREAD

**Issue by thelaurence** [thyer/CS340winter2016#81]
Here's the output from the console:
```
not your turn 2
End of update state = client.states.NotYourTurn@66a3b018
Increase amount of BRICK
Increase amount of BRICK
Increase amount of BRICK
Increase amount of ORE
not your turn 1
End of update state = client.states.NotYourTurn@1a5945
not your turn 1
End of update state = client.states.NotYourTurn@c5979e4
normal state
End of update state = client.states.Normal@7209d53d
```
Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/10649804/13449731/9202ce08-dfeb-11e5-954f-6ccc1b0357cf.png)

Just can't click anything. That's the best description I can come up with.

**Comment by hunterrees** [comment]
@thelaurence Do you have any other details on how to replicate?

**Comment by thelaurence** [comment]
@hunterrees sorry for the lack of detail. The Game History in the screenshot is probably the best record of what happened immediately before the lock-up. I was logged in as Sam, rolled a 6, and after pressing OK on the RollResultView, the client was non-responsive. You can see in the Game History that 2 of the AI players had rolled 7's previous to my rolling a 6, but I only had to discard on the first 7.

I haven't replicated this in subsequent games.
