### ISSUE TITLE
Domestic Trade does not update elements

### ISSUE THREAD

**Issue by nevans224** [thyer/CS340winter2016#82]
I traded a wheat for a brick and nothing happened. I don't know if it was rejected or if the person couldn't trade. Maybe the domestic Trade doesn't work at all?

**Comment by nevans224** [comment]
P3, team 18, phase 2

**Comment by thelaurence** [comment]
We discovered that @nevans224 was playing against AI's when he encountered this issue and the LARGEST_ARMY AI's are programmed to refuse all trades, so naturally he would not have seen any changes in his resource count. Closing as non-issue. Domestic trade appeared to work fine between two human players..
