### ISSUE TITLE
List of games does not update from server

### ISSUE THREAD

**Issue by thelaurence** [thyer/CS340winter2016#83]
Started fresh demo server. Started two fresh clients. Logged in as Sam on one and Pete on the other. Created new game as Sam and the game never appears in the games list on Pete's client. Screenshots:

![image](https://cloud.githubusercontent.com/assets/10649804/13450072/c058c002-dfee-11e5-8814-76da0b6017cf.png)

![image](https://cloud.githubusercontent.com/assets/10649804/13450075/cc16ea4a-dfee-11e5-9fd9-07140935c17d.png)

**Comment by hunterrees** [comment]
The TAs told us that it was not required to have the join game view update once you logged in

**Comment by thelaurence** [comment]
Haha I should have talked to the TA's! Thought this was required for some reason.

**Comment by thelaurence** [comment]
Closing. Invalid.
