### ISSUE TITLE
Game freezes on first role

### ISSUE THREAD

**Issue by sadler-j** [thyer/CS340winter2016#85]
This is likely a modal issue. It doesn't happen every time, but sometimes after the first player's role of the dice the game freezes. It likely doesn't close out of the roll frame (or a previous frame) properly, thus causing it to lock.

**Comment by misterpink14** [comment]
Do you mind doing a screencast of this? I haven't been able to replicate it. Thanks

**Comment by sadler-j** [comment]
I'll give it a shot. It definitely doesn't happen every time. I haven't figured out what might cause it.

**Comment by misterpink14** [comment]
Thanks!

**Comment by sadler-j** [comment]
I've already showed you this, but this comment is for documentation. It has a tendency to freeze for the first player after the first role. Restarting the client does fix the issue.
