### ISSUE TITLE
Can join a full game right after registering

### ISSUE THREAD

**Issue by skydrennan** [thyer/CS340winter2016#88]
Right after you register a new player, you can join any game, even if it is full. When you login again as that player, it works correctly, but for that first turn there are errors

**Comment by thyer** [comment]
@skydrennan Does this mean there are five players in the game? Or does it kick someone out?

**Comment by skydrennan** [comment]
I believe it only shows 4 players still in the game, and the 5th one doesn't ever render a map, but they are allowed to click join and pick a color and be brought to the game screen, if that makes sense? When you log back in it still shows the correct 4 players in the game.

**Comment by thyer** [comment]
Marking as dupe related to game Index defaulting to zero, still giving points to @skydrennan for finding this.
