### ISSUE TITLE
Game breaks after finishing turn

### ISSUE THREAD

**Issue by skydrennan** [thyer/CS340winter2016#91]
After the 2nd player's first real turn, in every game I tried, I was unable to continue on. It would never go to the 3rd player's turn.

**Comment by thyer** [comment]
Related to game index

**Comment by thyer** [comment]
Guys, I'm seeing a lot of remaining bugs left in here. Just tried to start a new game fresh after registering and it killed the client. Rejoining allowed normal gameplay to continue, but then I had to place roads unto infinity.
