### ISSUE TITLE
2 clients can be the same color

### ISSUE THREAD

**Issue by skydrennan** [thyer/CS340winter2016#92]
ONLY if they are both logged in before either one chooses the game to be in. I'm sure this is because you load the list of games as soon as you log in, and then don't reload it again. Very small bug!

**Comment by KasiKarra** [comment]
We will look into it, but our poller is also set to poll at 3 second intervals, so you may just choose colors too fast

**Comment by thyer** [comment]
Since the client sends update instructions to the server, this is considered incorrect behavior. As a suggestion, you might query the server upon color selection to do an instant check before actually patching the command through if it's still a valid request.
