### ISSUE TITLE
Maritime Trade Overlay display issue

### ISSUE THREAD

**Issue by tcashcroft** [thyer/CS340winter2016#95]
The selected resources don't highlight correctly. (Super minor bug, but it looks bad...)
![grayedoutoptions](https://cloud.githubusercontent.com/assets/17575428/13451777/761e9dd4-dfff-11e5-8965-81b0f7a67ffc.png)

**Comment by tclaw46** [comment]
The selected resources in the demo game are also grayed out and not highlighted so I don't see reason this needs to be fixed.
